### ISSUE TITLE
New mirror: access for all maintainers

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#10]
```
# dnf config-manager --add-repo=https://gitlab.com/FedoraUnited/repository/raw/master/unitedrpms.repo
```

Hosted on [Gitlab](https://gitlab.com/), 10 GB free space for each repository. Here's the mirror of [Fedora United](https://gitlab.com/FedoraUnited).

I need the @kuboosoft and @sergiomb2 logins on Gitlab (login from Github account is supported), then add it to organization and every maintainer will have access to RPM repository.

**Comment by sergiomb2** [comment]
https://gitlab.com/u/sergiomb2

**Comment by paulcarroty** [comment]
@sergiomb2 done. @kuboosoft ?

**Comment by kuboosoft** [comment]
[HERE](https://gitlab.com/u/davidjeremias82)

**Comment by paulcarroty** [comment]
@kuboosoft 

![](http://thumbs.dreamstime.com/z/access-granted-24907039.jpg)

**Comment by paulcarroty** [comment]
@kuboosoft https://github.com/FedoraUnited/packages/wiki/How-to-work-with-RPM-Repository

**Comment by kuboosoft** [comment]
@paulcarroty and github? ; I can't check  repositories in gitlab and maintain updated; maybe you can maintain updated. Remember the majority hands is available in github; each repository will receive reports of bugs, or a reminder about update it... and gitlab isn't very popular...Torvals uses github... Why you not only upload src.rpm in gitlab ;)

**Comment by paulcarroty** [comment]
@kuboosoft man, if you can be a sponsor and buy Github Enterprize account for us, it's will be great. We use Gitlab **as RPM repo only** because it's free 10 GB per repo. More users => more traffic, and we can be banned in any moment from Google Cloud.

If you can't push new rpm to Gitlab, we can do it. Just write about new packages in #9 .

And yes, my congratulations 

```
$ du -sh repository/
1.2G	 repository/
```

**Comment by sergiomb2** [comment]
>  we can be banned in any moment from Google Cloud.

I don't see why and how we will be banned from Google Cloud, it is my personal account and I don't do anything illegal. 

Anyway I agree in use Gitlab as RPM repo only and btw remove rpms from other repos on github , except perhaps in packages ( https://github.com/FedoraUnited/packages/ )

**Comment by paulcarroty** [comment]
> btw remove rpms from other repos on github , except perhaps in packages ( https://github.com/FedoraUnited/packages/ )

I suggest to do what maintainer want. One goal - access to spec and SRPM must be easy 'in one click'.

**Comment by kuboosoft** [comment]
Anyway; we must be careful with our software; not to publish proprietary license programs. In github only publish .spec sources and src.rpm (rpms only, someone here want rebuilt and upload it in the repo and mirror)

**Comment by paulcarroty** [comment]
@kuboosoft yep, and ideally we need a backup all our GH repos. But I currently doesn't have the ideas how we can do it.

**Comment by kuboosoft** [comment]
@paulcarroty is a  tired job ; so avoid software, completely closed; example Opera es closed but we can redistribute it; without modified or apply reverse engineering.
