### ISSUE TITLE
gstreamer1 dependency conflicts

### ISSUE THREAD

**Issue by tdgroot** [UnitedRPMs/packages#100]
I'm having some dependency conflicts around gstreamer1 since I added the unitedrpms repository..

```
~ sudo dnf upgrade --best
Last metadata expiration check: 0:09:58 ago on Tue Mar  7 17:37:03 2017.
Error: cannot install both gstreamer1-1.11.2-1.20170224gite4a7200.fc24.x86_64 and gstreamer1-1.8.3-1.fc24.x86_64.
cannot install both gstreamer1-plugins-base-1.11.2-1.fc24.x86_64 and gstreamer1-plugins-base-1.8.3-2.fc24.x86_64.
package openssl-freeworld-libs-2:1.0.2k-3.fc24.x86_64 obsoletes openssl-libs < 2:1.0.2k-3.fc24 provided by openssl-libs-1:1.0.2k-1.fc24.i686.
package krb5-libs-1.14.4-4.fc24.i686 requires libcrypto.so.10, but none of the providers can be installed.
package openssl-full-2:1.0.2k-2.fc24.x86_64 requires openssl-full-libs(x86-64) = 2:1.0.2k-2.fc24, but none of the providers can be installed
(try to add '--allowerasing' to command line to replace conflicting packages)
```

Any suggestions?

**Comment by kuboosoft** [comment]
dnf -y remove gstreamer1 && dnf -install gstreamer1 gstreamer1-plugins-ugly

krb5-libs-1.14.4-4.fc24.i686?? who installs it? can you remove it without affect system?

Here the real problem is openssl! we need resolve it!
compat-openssl10 = libcrypto.so.10
openssl-full= openssl-freeworld

**Comment by sergiomb2** [comment]
first :
`dnf upgrade --exclude="openssl*"`
you don't need openssl for other packages 
second: please output 
rpm -qa | grep openssl

Thanks
