### ISSUE TITLE
vlc conflicts with live555

### ISSUE THREAD

**Issue by dodona2** [UnitedRPMs/packages#101]
install vlc resultts in:

Installing:
 **vlc          x86_64     3.0.0-24.20170302git989bc9d.fc25**      unitedrpms     1.5 M
 v**lc-core     x86_64     3.0.0-24.20170302git989bc9d.fc25**      unitedrpms     8.6 M
**Downgrading**:
 **live555      x86_64     2016.09.22-1.fc25**                     unitedrpms     363 k

**Comment by kuboosoft** [comment]
Thanks! we only needs rebuild vlc with the new live555, 24 hours ;)

**Comment by dodona2** [comment]
thanks a lot!

**Comment by dodona2** [comment]
got it!
Again thanks a lot!
> Upgraded:
>   live555.x86_64 2017.01.26-2.fc25                                                  
>   vlc.x86_64 3.0.0-25.20170307git4ae3d6f.fc25                                       
>   vlc-core.x86_64 3.0.0-25.20170307git4ae3d6f.fc25
