### ISSUE TITLE
wine conflicts with gstreamer1

### ISSUE THREAD

**Issue by dodona2** [UnitedRPMs/packages#102]
install wine:
Installing:
 gstreamer1                        i686       1.10.4-1.fc25       updates     1.2 M
 gstreamer1-plugins-base           i686       1.10.4-1.fc25       updates     1.4 M
 mpg123-libs                       i686       1.23.8-4.fc25       updates     204 k
 wine                              x86_64     2.2-1.fc25          updates      55 k
 wine-alsa                         i686       2.2-1.fc25          updates     107 k
 wine-capi                         i686       2.2-1.fc25          updates      61 k
 wine-cms                          i686       2.2-1.fc25          updates      76 k
 wine-core                         i686       2.2-1.fc25          updates      24 M
 wine-ldap                         i686       2.2-1.fc25          updates     130 k
 wine-openal                       i686       2.2-1.fc25          updates      68 k
 wine-opencl                       i686       2.2-1.fc25          updates      66 k
 wine-pulseaudio                   i686       2.2-1.fc25          updates      98 k
 wine-twain                        i686       2.2-1.fc25          updates      85 k
Downgrading:
 gstreamer1                        x86_64     1.10.4-1.fc25       updates     1.2 M
 gstreamer1-devel                  x86_64     1.10.4-1.fc25       updates     448 k
 gstreamer1-plugins-base           x86_64     1.10.4-1.fc25       updates     1.5 M
 gstreamer1-plugins-base-devel     x86_64     1.10.4-1.fc25       updates     306 k
 mpg123                            x86_64     1.23.8-4.fc25       updates     110 k
 mpg123-devel                      x86_64     1.23.8-4.fc25       updates     240 k
 mpg123-libs                       x86_64     1.23.8-4.fc25       updates     202 k
 mpg123-plugins-jack               x86_64     1.23.8-4.fc25       updates      19 k
 mpg123-plugins-pulseaudio         x86_64     1.23.8-4.fc25       updates      16 k

**Comment by kuboosoft** [comment]
Hi! You can't install diferents versions and platforms of gstreamer1, and unitedrpms doesn't provides i686, only x86_64 packages sorry :( wine is a problem for all, because it installs packages of 32bits... I recommend rebuild gstreamer1 for i686 if you want use the latest gstreamer1.

**Comment by dodona2** [comment]
no idea how the 32bit gstreamer1 came on my machine. I removed it manually. Thanks a lot for your offer. Please notify me when you'll find some spare time.
