### ISSUE TITLE
chromium-pepper-flash installed in /usr/lib64/chromium-browser 

### ISSUE THREAD

**Issue by akeyjadu** [UnitedRPMs/packages#105]
Hi,
Am I missing something re this package ?
The chromium-freeworld package you provide in UnitedRPMs is installed to /usr/lib64/chromium but this package is installed to /usr/lib64/chromium-browser which makes it quite broken and incompatible with each other.
Is there a reason for these two being distinct ?

Distro: Fedora 25 KDE

**Comment by kuboosoft** [comment]
Can you write the next?...

```
dnf provides chromium-pepper-flash
rpm -q chromium-pepper-flash
```
Our chromium-pepper-flash provides a symlink to Chromium Fedora, useful if you want play contain flash with Chromium Fedora....  But we should't provide it. Is a gift for the community using the Fedora package... chromium-freeworld is different and  our chromium-pepper-flash provides capability with our packages... 

https://github.com/UnitedRPMs/chromium-pepper-flash/blob/master/chromium-pepper-flash.spec#L61
