### ISSUE TITLE
Gstreamer1 in conflict with libreoffice

### ISSUE THREAD

**Issue by melissa696969** [UnitedRPMs/packages#106]
Hello everybody
Sorry for my english, i am french 

Gstreamer1 conflicts with libreoffice 5.3.2.1.3 

During an `sudo dnf upgrade`
I get this (3 packets in conflict) See screenshot
https://www.pixenli.com/images/1490/1490867307041142100.png

If I try `sudo dnf upgrade --best --allowerasing` 
I am told to remove libreoffice (I use it for my work therefore indispensable for me) see screenshot
https://www.pixenli.com/images/1490/1490868486021347700.png

And here is the list of gstreamer installed on my pc
https://www.pixenli.com/images/1490/1490868884029482300.png

It's better that I wait for an update. ??
Or a manipulation that I do not know, can resolve this conflict.

Even if the problem is not serious, I also wanted to inform you of the current bug.

distribution : Fedora 27 Rawhide 64bits Cinnamon (up to date)

Thank you for your work, and this wonderful repository that is useful to listen to my music .mp3 and .m4a :) 

Melissa.

**Comment by paulcarroty** [comment]
Hello @melissa696969, thank you for very good bugreport!

`# dnf --best --allowerasing install libreoffice` works for me.

**Comment by paulcarroty** [comment]
@kuboosoft I think we can do nothing, just wait for new LO rebuild:

```
# dnf --best install libreoffice
Last metadata expiration check: 0:15:41 ago on Thu Mar 30 14:05:20 2017 EEST.
**Error: gstreamer1-plugins-bad-free-1.11.2-1.fc26.i686 has inferior architecture**
  - package gstreamer1-plugins-bad-free-gtk-1.11.2-1.fc26.x86_64 requires gstreamer1-plugins-bad-free = 1.11.2-1.fc26, but none of the providers can be installed
  - problem with installed package gstreamer1-plugins-bad-free-1.11.2-2.fc27.x86_64
  - cannot install both gstreamer1-plugins-bad-free-1.11.2-1.fc26.x86_64 and gstreamer1-plugins-bad-free-1.11.2-2.fc27.x86_64
  - cannot install both gstreamer1-plugins-bad-free-1.11.2-2.fc27.x86_64 and gstreamer1-plugins-bad-free-1.11.2-1.fc26.x86_64
  - package libreoffice-gtk3-1:5.3.2.1-3.fc27.x86_64 requires gstreamer1(element-gtksink)()(64bit), but none of the providers can be installed
  - package libreoffice-core-1:5.3.2.1-3.fc27.x86_64 requires libreoffice-gtk3(x86-64) = 1:5.3.2.1-3.fc27, but none of the providers can be installed
  - package libreoffice-base-1:5.3.2.1-3.fc27.x86_64 requires libcomphelper.so()(64bit), but none of the providers can be installed
  - package libreoffice-1:5.3.2.1-3.fc27.x86_64 requires libreoffice-base(x86-64) = 1:5.3.2.1-3.fc27, but none of the providers can be installed
  - conflicting requests
```

**Comment by melissa696969** [comment]
Nothing with pleasure for the bug report.

LO has been updated this morning, and the dependency problem has been going on for about a week, following the installation of the ""pocl-devel"" package to fix an in-time crash on LO.
https://www.pixenli.com/images/1490/1490878949007937500.png

le problème n'est pas gênant en soi, et ça permet de remonter le bug jusqu'à vous, pour vous en informez :)

**Comment by paulcarroty** [comment]
@melissa696969 our gstreamer1 package rewrite the original in Fedora 27 (`gstreamer1-plugins-bad-free-1.11.2-1.fc27` vs `gstreamer1-plugins-bad-free-1.11.2-1.fc26`). That's absolutely the same software (now compiler and base libs from F26 = F27). Downgrade our package will be not technically correct because Rawhide now is the F27 not F26.

Anyway, we're glad for any voice from the other side :)

**Comment by kuboosoft** [comment]
I only can rebuild with a new release, it will update without problem; why rawhide has a gstreamer1..badfree.fc26? haha funny no? wait some hours please, thanks for your report @melissa696969

**Comment by paulcarroty** [comment]
@melissa696969 @kuboosoft 

```
Hi,

I tried but it seems things are broken right now, will try again later.

https://koji.fedoraproject.org/koji/taskinfo?taskID=18682965

Wim


----- Original Message -----
From: "Pavlo Rudyi" <paulcarroty@riseup.net>
To: "Wim Taymans" <wtaymans@redhat.com>
```

**Comment by paulcarroty** [comment]
Win: https://koji.fedoraproject.org/koji/buildinfo?buildID=874230

**Comment by kuboosoft** [comment]
@paulcarroty gstreamer1 isn't the problem is libreoffice who changed your "requires" with a specific version of the plugin gstreamer1-plugins-bad-free; the plugin isn't necessary for build; but the maintainer puts in "Requires" the same version in Fedora; bad decission. Do you destand? the fast solution and avoid rebuild LO, [check the new package](https://github.com/UnitedRPMs/libreoffice-gtk3), chuck norris style ... 

You can report it in bugzilla, "Delete the specific version of gstreamer1-plugins-bad-free in requires" I can solve the problem without uses our version...

**Comment by melissa696969** [comment]
Hello
sorry for the delay
Heavy work in the residence and temporary cut of the internet.
I would do the upgrades tomorrow by bringing my pc to work.
For the Ananconda Team repository, I will check if it is enabled, and would do the handling as advised.

Thanks for your work, and your responsiveness. 
A nice project for us Fedorians under Rawhide;)

**Comment by paulcarroty** [comment]
>  A nice project for us Fedorians under Rawhide;)
Because Rawhide was the first goal of our project 😸

**Comment by kuboosoft** [comment]
@melissa696969 you can sync now!! enjoy! :)

**Comment by melissa696969** [comment]
hello ;)
sorry for the delay.
After the updates, everything is back in order. 
No more conflict
Thank you very much for your work and your responsiveness.
I love the linuxian community :) :) :) :) :) :D

**Comment by paulcarroty** [comment]
@melissa696969 thankfully for Fedora maintainer :) https://koji.fedoraproject.org/koji/buildinfo?buildID=874302

**Comment by kuboosoft** [comment]
@paulcarroty the Fedora maintainer?? hahaha
 `dnf info libreoffice-gtk3 && rpm -q libreoffice-gtk3`
