### ISSUE TITLE
virtualbox not installing on Fedora 25

### ISSUE THREAD

**Issue by rattaro** [UnitedRPMs/packages#107]
platform:  fedora 25
Issue:  VirtualBox not installing properly
How to reproduce:
1.  sudo dnf update
2.  sudo dnf install VirtualBox => Error: nothing provides VirtualBox-kmod = 5.1.18 needed by VirtualBox-server-5.1.18-2.fc25.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages)
3.  sudo dnf install VirtualBox --allowerasing => Error: nothing provides VirtualBox-kmod = 5.1.18 needed by VirtualBox-server-5.1.18-2.fc25.x86_64

Expected behavior:  should install without issue.  Maybe VirtualBox-kmod is not an included dependency?

**Comment by paulcarroty** [comment]
@rattaro should be fixed. I recommend to use an akmod. If the problem still exist - just reopen this issue.

**Comment by kuboosoft** [comment]
I am prefer a dkms... clean and simple!!
