### ISSUE TITLE
Mass rebuild rules

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#108]
There's a tree - https://trello.com/b/sp1OONkU/the-massrebuild-tree, tested IRL and works good.

**If you need to bump package N then need to rebuild all (N+1) trees**.

@kuboosoft and yep, I don't want to see the shit 'this is not my package' anymore. If you can't fully complete your work - no need to begin it. Learn how a team works.

About major and minor updates - it's better to use major versions like `3.2`, `3.3`, not `3.2.4`, `3.2.6` for all core packages like x26? and ffmpeg.

**Comment by kuboosoft** [comment]
https://github.com/UnitedRPMs/packages/wiki/Our-Git-repositories-and-build-tools

**Comment by paulcarroty** [comment]
> because you updated the package in the same moment in the build process

Sorry of course, but how I can detect if you build something? See your repos every time? Write the simple page with your CI status. Be honest, we need a status page. 

> If you put a repository here in unitedrpms then you need maintain it

Feudalism was ended 400 years ago. Yep, you need to maintain it, but waiting a week or month if other package is broken and no signal from other maintainer is stupid. There's a command work. I you begin a mass rebuild **then must build all trees** because other maintainer don't will be try all other broken packages by you. If you can't automate the rebuild of 5 packages - request help or learn other PL over Bash.

**Comment by kuboosoft** [comment]
Remember the current massive rebuild is thanks to [your error](https://github.com/UnitedRPMs/ffmpeg/commits/master)! I canot discuss again it; Do you want to break my balls?
https://github.com/UnitedRPMs/packages/wiki

**Comment by paulcarroty** [comment]
@kuboosoft my error? Update the package is the error? 😃 You're funny.
