### ISSUE TITLE
Unable to execute Tribler

### ISSUE THREAD

**Issue by frafra** [UnitedRPMs/packages#109]
1. Missing dependency python-feedparser
    `ImportError: No module named feedparser`
2. Missing SQL script
    `OSError: SQL script doesn't exist: /usr/share/tribler/Tribler/schema_sdb_v28.sql`

**Comment by sergiomb2** [comment]
what is your fedora version ?

**Comment by frafra** [comment]
Fedora 25.

**Comment by sergiomb2** [comment]
thanks for the report unfortunately I can't fix it soon , we have tribler  7.0.0-0.alpha1    to test

**Comment by kuboosoft** [comment]
@frafra We have tribler 7.0.0.b now!; I am testing, but I don't have the know fot test it completely.

**Comment by frafra** [comment]
@kuboosoft how can I test it?

**Comment by sergiomb2** [comment]
@kuboosoft  me too , can you commit something , are you using new graphic interface changed from wxsomething to another thing that I don't recall now ? 
Thanks

**Comment by kuboosoft** [comment]
@frafra @sergiomb2 @paulcarroty https://github.com/UnitedRPMs/tribler/releases/tag/7.0.0-1.b
