### ISSUE TITLE
UnitedRPMs/F25 is *completely* broken.

### ISSUE THREAD

**Issue by speachy** [UnitedRPMs/packages#110]
```
[pizza@kalamata ~]$ sudo dnf update
Last metadata expiration check: 0:22:38 ago on Wed Apr 26 20:38:10 2017.
Dependencies resolved.
================================================================================
 Package               Arch   Version                          Repository  Size
================================================================================
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 ffmpeg-libs           x86_64 3.3-1.fc25                       unitedrpms 6.3 M
 gstreamer1            x86_64 1.11.2-1.20170224gite4a7200.fc25 unitedrpms 1.2 M
 gstreamer1-devel      x86_64 1.11.2-1.20170224gite4a7200.fc25 unitedrpms 451 k
 gstreamer1-plugins-base
                       x86_64 1.11.2-1.fc25                    unitedrpms 1.5 M
 gstreamer1-plugins-base-devel
                       x86_64 1.11.2-1.fc25                    unitedrpms 310 k
 gstreamer1-plugins-base-tools
                       x86_64 1.11.2-1.fc25                    unitedrpms  39 k
 libva-intel-driver    x86_64 1.7.3-1.fc25                     unitedrpms 382 k
 mpg123                x86_64 1.24.0-4.fc25                    unitedrpms 123 k
 mpg123-devel          x86_64 1.24.0-4.fc25                    unitedrpms  44 k
 mpg123-libs           x86_64 1.24.0-4.fc25                    unitedrpms 181 k
 mpg123-plugins-portaudio
                       x86_64 1.24.0-4.fc25                    unitedrpms  15 k
 mpg123-plugins-pulseaudio
                       x86_64 1.24.0-4.fc25                    unitedrpms  14 k
 openssl-freeworld     x86_64 2:1.0.2k-5.fc25                  unitedrpms 505 k
 openssl-freeworld-devel
                       x86_64 2:1.0.2k-5.fc25                  unitedrpms 1.5 M
 openssl-freeworld-libs
                       x86_64 2:1.0.2k-5.fc25                  unitedrpms 2.4 M
 vlc                   x86_64 3.0.0-31.20170417git4a4e0c5.fc25 unitedrpms 1.5 M
 vlc-core              x86_64 3.0.0-31.20170417git4a4e0c5.fc25 unitedrpms 8.7 M
 vlc-devel             x86_64 3.0.0-31.20170417git4a4e0c5.fc25 unitedrpms 245 k
 x265-libs             x86_64 2.3-2.20170417git97492ac.fc25    unitedrpms 1.5 M
Skipping packages with broken dependencies:
 libtxc_dxtn           i686   1:1.0.1-1.gitef072983.fc26       unitedrpms  18 k
 libva-intel-driver    i686   1.7.2-1.fc26                     unitedrpms 377 k
```

Note how literally *everything* here is from unitedrpms.

And if you try to use --best --allowerasing, you get such gems as dnf trying to remove F25's 'wine', 'gtk2' and 'gtk3' i686 packages. as well as x86_64 unitedrpms packages like 'gstreamer1-plugins-bad-freeworld'

Please, if unitedrpms isn't going to be sufficiently well-maintained to be internally consistent (to say nothing of remaining compatible with upstream Fedora) then just take it offline so more folks don't end up in this mess.

**Comment by kuboosoft** [comment]
[Skipping packages with broken dependencies:
libtxc_dxtn i686 1:1.0.1-1.gitef072983.fc26 unitedrpms 18 k
libva-intel-driver i686 1.7.2-1.fc26 unitedrpms 377 k](url)

Thanks... we will check why we have libtxc_dxtn and  libva-intel-driver from F26 in F25.
I ask you, was you install steam?

**Comment by paulcarroty** [comment]
@kuboosoft  libva-intel-driver updated to 1.7.3 in F25 and 1.8.1 for F26-27.

@speachy there's not a commercial company where you can buy the support. Welcome to the open source.

**Comment by speachy** [comment]
@kuboosoft Yes, I have steam installed, originally from the fedora-steam repo on negativio17.org.  I originally got the libtxc stuff from that repo too, which has both i686 and x86_64 versions and both were installed.  (The conflict was due to UnitedRPMs not having an x86_64 version built)

That said, steam isn't the problem I'm grumpy about -- it's gstreamer1. The i686 and x86_64 package versions need to be kept in sync, and unitedrpms did not build i686 versions of what they're uploading.  The correct way to handle this is to either rebuild both arches of everything, or stick to just building the -freeworld codec packages for the gstreamer packages that match what Fedora has already bundled.

(And then there's the openssl-freeworld fiasco that broke an otherwise-stock F25 server installation, because it was built needing executable stacks and whatnot, breaking the Fedora SELinux rules for critical daemons like, oh, openssh.  It took me two weeks to get this system back online owing to the fact it was in a very remote location..)

Meanwhile, @paulcarroty, I get that there's no commercial support (and thus no grounds to expect any sort of SLA), but if unitedrpms as-released isn't even internally consistent, much less compatible with an out-of-the-box Fedora installation, then it fails utterly at its entire _raison d'etre_.

Say what you will about RPMFusion and its "stupid breaucracy" (to quote the UnitedRPM home page), said breaucracy prevents this sort of thing from happening.

**Comment by paulcarroty** [comment]
> The i686 and x86_64 package versions need to be kept in sync, and unitedrpms did not build i686 versions of what they're uploading. The correct way to handle this is to either rebuild both arches of everything, or stick to just building the -freeworld codec packages for the gstreamer packages that match what Fedora has already bundled.

Seems like it's true. We talked about only gstreamer1 with patented codecs, but @kuboosoft stubbornly continues build it. @kuboosoft, can you explain with some kind of logic?

> And then there's the openssl-freeworld fiasco

Created by @sergiomb2, the RPMFusion and Fedora maintainer. Surprise!

>  but if unitedrpms as-released isn't even internally consistent, much less compatible with an out-of-the-box Fedora installation, then it fails utterly at its entire raison d'etre.

@speachy, sorry, but it is how things works. Bug happens, we fix them. Today it's consistent, tomorrow will be broken with latest updates. We actually do what we can. You are not satisfied? Give us a good *practical* idea or something like. Ah, also you can still to believe that the bureaucracy will save the world 😸 

P.S. Automation tests is neccesary for URPMS. Now I'm learn new technologies and probably can invest my code.

**Comment by speachy** [comment]
Serious question -- What's the goal of UnitedRPMs?  It's clearly not the end-user experience, because if that was the case, you'd have *yanked* the gstreamer1 packages (or downgraded to an older one) while waiting for @kuboosoft to explain him/herself.  A developer that refuses to fix problems (even if only by inaction) needs to be overruled.  The buck has to stop with _someone_.

Call that whatever you like (process or even bureaucracy) but a project's purpose is to serve its users' needs.  If UnitedRPMs only seeks to be a playground for it's developers (ie its users are its developers), that's quite alright, as long as everyone is up-front about it.  Although now that I re-read the text on the homepage, that's more or less what you claim it to be.

(FWIW, I say this as someone who's been actively contributing and maintaining F/OSS stuff for the better part of two decades, and also as someone who's off-and-on maintained RH/Fedora repositories of backports and other stuff during that time too.  It takes a nontrivial amount of ongoing effort to just remain in place!)

**Comment by kuboosoft** [comment]
@speachy you only cry; but I can't see your contribution (The purpose of project is clear, and its focus the is contribution)... I can make i686 packages for gstreamer (easy), but in unitedrpms our focus is 64bits; who sane installs a gstreamer1 of i686 in a machine with 64bits? It is stupid. Why "wine" requires a package of 32 bits? I am not a developer, I am only packager, for me; I will happy if wine disappears... 

You can ask, Who uses a 32 bits machine in a email list in Fedora (You will hear crickets)... You can see the current changelog in the most packages, in UnitedRPMs ; Who is updating, patching, etc. If you make a "commit" o "pull request" on github, welcome... Because, you only want manipulate the situation a your stupid issue with wine... and a installation of Steam from Negativo...  With those same cries, contact  to wine or the packager of wine for solve it, but not unitedrpms... Said he, you need a x86_64 for wine...

Only people with wine is unhappy, in UnitedRPMs... ("Entire repository is broken" hahaha)  Surely @paulcarroty  can rebuild gstreamer1 packages for 32 bits ... I can not support it because I do not have a 32 machine for test it ...... the man only put repositories but forgot maintain it... remember nvidia? now libva-intel-driver for 32bits... I rebuilt it now and solved the problem...

I'm 100% sure @paulcarroty  will close the issue, because the man does not like it when we touch him ...

```
[makerpm@localhost ~]$ dnf clean metadata && dnf provides libva-intel-driver
44 files removed
determining the fastest mirror (3 hosts).. done.
Fedora 25 - x86_64                              264 kB/s |  50 MB     03:15    
Fedora 25 openh264 (From Cisco) - x86_64        4.3 kB/s | 2.8 kB     00:00    
Fedora 25 - x86_64 - Updates                    311 kB/s |  22 MB     01:12    
unitedrpms                                      186 kB/s | 925 kB     00:04    
enjoy                                           3.0 MB/s |  33 kB     00:00    

libva-intel-driver-1.7.3-1.fc25.x86_64 : HW video decode support for Intel
                                       : integrated graphics
Repositorio        : @System

libva-intel-driver-1.7.3-1.fc25.x86_64 : HW video decode support for Intel
                                       : integrated graphics
Repositorio        : unitedrpms

libva-intel-driver-1.7.3-2.fc25.i686 : HW video decode support for Intel
                                     : integrated graphics
Repositorio        : unitedrpms
```

**Comment by speachy** [comment]
@kuboosoft -- Whether or not you use wine, it is a supported part of Fedora.  If you are going to bill UnitedRPMs as an extension of Fedora or even as "rawhide for RPMFusion"

So, respectfully, this is your package, and your mess.  If you want users, you need to get your act together.

Good day.

**Comment by kuboosoft** [comment]
@speachy Your disaster is mix various repositories (steam from negativo)... not our packages. Common sense! The users using unitedrpms is big; common people doesn't install the stupid wine... for it; you have a windows machine or a dual boot, or in extreme cases a virtual machine... but not wine...

The packages have no owner; here is contribution... But generally has maintainers:

1) Who put the repository in github.. (the first maintainer)
2) Our maintainers
3) Our users

**Comment by speachy** [comment]
@kuboosoft:

Wine has many advantages over both dual-booting and virtual machines -- Including not having to pay for a Windows license in order to run a bit of Windows software.  But that is besides the point -- you don't get to tell me (or anyone else for that matter) that their use cases are invalid.

Why must I have to repeat myself by pointing out again that the gstreamer1* package mess has *nothing* to do with my mixing repos?   it is conflicting purely with packages that are part of bone-stock Fedora 25 -- Even if I didn't have wine installed, it would have still forced the removal of core system libraries like gtk2 and gtk3 (and everything that dependened on them).

UnitedRPMs is your collective sandbox and what you do with it is entirely your perogative.  So, fix this properly, or not; I honestly don't care as no longer use these repos or their packages. I've learned my lesson.

**Comment by kuboosoft** [comment]
Even if I didn't have wine installed, it would have still forced the removal of core system libraries like gtk2 and gtk3 (and everything that dependened on them).

Why? for a stupid installation of gstreamer1 (32bits) in a machine of 64bits? hahaha; can you write me here how to install a the gstreamer1 of 32bits without wine, without google? the gstreamer is working fine, is your Steam buddy...

libtxc_dxtn and libva-intel-driver isn't part of Fedora Project, then is contradictorious. You have problems because you installed steam from other thirdparty repository with dependencies; and you reclaims to unitedrpms for it, is joke? remove and disable negativo repository and go back here... for a real problem. Our Steam works fine with the current dependencies in unitedrpms...

Here our [WIKI](https://github.com/UnitedRPMs/packages/wiki) about other questions...
