### ISSUE TITLE
Second CI for libva-intel-driver

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#111]
@kuboosoft why we need it? For more solid look? Maybe you need to add all available CI?

**Comment by kuboosoft** [comment]
@paulcarroty I don't need it; but Steam uses it... We can't forget maintain it for i686 and x86_64; the shippable CI build only our version in i686... I put unibuild task in mode test... if you need build a version; only put the fedora version and includes "-c true" for sync the results in the cloud...
