### ISSUE TITLE
Prototype of website and our next steps

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#14]
Check it now: https://fedoraunited.github.io/

Any ideas @sergiomb2 @kuboosoft?  What content I need to add?

My suggestions: get any free domain and share information about our project. I can write an article in my blog. 

The brand question to @kuboosoft: we're steal your trademark, bro :smile: What you think about it? I don't know, maybe we'll enable some monetization for servers in future. I will to see any productive suggestions.

Big thanks to all.

**Comment by kuboosoft** [comment]
Hey only puts 'Contributors'; without direct links to user in github; and write the origin about the project.  Maybe includes a funny comic as http://goo.gl/sWs3Z ; check the slide 5 (troll). Marketing ;)

**Comment by sergiomb2** [comment]
> Check it now: https://fedoraunited.github.io/
> 
> Any ideas @sergiomb2 @kuboosoft? What content I need to add?

Very nice, congratulations  , yes many things and ideas, but is weekend ! , so my plan is rest a little bit :D , but about backups you need backup .spec and patches very light stuff , because rpm and src.rpm can always be generated again, that is the point.

**Comment by paulcarroty** [comment]
@kuboosoft 

> Maybe includes a funny comic as http://goo.gl/sWs3Z ; check the slide 5-9

Great, we need to create a `.gif` from these slides :+1: 

> Please do not use the kuboosoft brand .

We talk about `Fedora United`. If you don't like that we use your brand and your G+ group, we need to change the name. 

> Monetization for this project?, maybe only donations Its very premature in this moment.

Not in this moment, after 1-2 months. I don't think that we'll get a lot of money, but maybe $10-20 will be enough for DigitalOcean/Leaseveb/Hetzner VPS and `koji/copr`. We definitely need it.

**Comment by kuboosoft** [comment]
Fedora United, is fine; is the origin; but is a serious problem for legal flags; example: 'Fedora Utils' changed your name because was contacted for legal Fedora; maybe United RPM; Enjoy RPM sounds great ;)
