### ISSUE TITLE
[Important] VOTING: New project name

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#15]
@kuboosoft was wrote:

> Fedora United, is fine; is the origin; but is a serious problem for legal flags; example: 'Fedora Utils' changed your name because was contacted for legal Fedora; maybe United RPM; Enjoy RPM sounds great ;)

Check also: https://fedoraproject.org/wiki/Legal:Trademark_guidelines

Any ideas @kuboosoft @sergiomb2 ?

**Comment by kuboosoft** [comment]
Puny name, serious project "funited"; I gave ideas; man, also adds something; for me is irrelevant the name; but read it  https://fedoraproject.org/wiki/Legal:Trademark_guidelines

**Comment by paulcarroty** [comment]
> https://fedoraproject.org/wiki/Legal:Trademark_guidelines

> Fedora®, the Fedora word design, the Infinity design logo, Fedora Remix, and the Fedora Remix word design, either separately or in combination, are hereinafter referred to as "Fedora Trademarks" and are trademarks of Red Hat, Inc.

We really new name. I don't have now any idea.

> "funited"

Not bad, but can be understand in uncensored context "f*ck united"

> for me is irrelevant the name; 

The name must be relevant for all - it must be original, light to remember and related with project style.

**Comment by paulcarroty** [comment]
What you think about `RPM Underground`?

**Comment by region51** [comment]
_RPM Future_

**Comment by kuboosoft** [comment]
sounds similiar rpmfusion=rpmfure
@paulcarroty Do you like "Need for Speed UnderGround" haha 
Funited (features united) make rpm, learn rpm, update rpm...

**Comment by paulcarroty** [comment]
@kuboosoft `rpmfuture` is good, but slightly more pathetic.

> Funited (features united) make rpm, learn rpm, update rpm...

Good as phrase, bad as name. So, I think we need a voting :smile:

**Comment by sergiomb2** [comment]
Unitedrpms, @region51 your user is familiar to me , but I don't remember from where ...

**Comment by paulcarroty** [comment]
@sergiomb2, stupid russian spammer :smile: 

[RPMFusion - muddy repository without adequate infrastructure](https://github.com/flacon/flacon/issues/30#issuecomment-201865374)

**Comment by region51** [comment]
>stupid russian spammer :smile:

А вот теперь по-русски озвучь это

**Comment by region51** [comment]
@paulcarroty ну, куда пропал, если не умешь общаться, то лучше промолчать и ничего не писать, а то что с rpmfusion беда, это факт медицинский, который никто не оспорит. А теперь ответь по поводу вышенаписанного.

**Comment by paulcarroty** [comment]
@region51 it's a joke :sweat_smile:

**Comment by paulcarroty** [comment]
So, time to change. Here's the the **all** variants from this thread:

1.  **FUnited**
2.  **United RPM**
3.  **Enjoy RPM**
4.  **RPM Underground**
5.  **UnitedRPMS**

Let's vote! Every human have every 1 vote. If we can't detect a winner, the second tour will be made.
@kuboosoft @region51 @sergiomb2

**Comment by paulcarroty** [comment]
4.

**Comment by sergiomb2** [comment]
5 :smile: @paulcarroty , you may do a pool in G+ ?

**Comment by paulcarroty** [comment]
@sergiomb2, we must ask @kuboosoft first ;-)

**Comment by region51** [comment]
_5._
_UnitedRPMs_

**Comment by kuboosoft** [comment]
5. UnitedRPMs

**Comment by kuboosoft** [comment]
@region51 = [negativo17](http://negativo17.org) ; welcome ;)

**Comment by paulcarroty** [comment]
Thanks all, we have a winner, UnitedRPMS.

**Comment by sergiomb2** [comment]
> @region51 = negativo17 ; welcome ;)

nan Negativo is Simon from Switzerland, anyway for me we may add region51 to admin group .

**Comment by paulcarroty** [comment]
@sergiomb2 @kuboosoft 

region51 != negativo
