### ISSUE TITLE
New URLS

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#16]
@kuboosoft , please fix in your G+ group:

```
# dnf config-manager --add-repo=https://unitedrpms.github.io/fedora-enjoy24.repo
```

Mirror:
```
# dnf config-manager --add-repo=https://gitlab.com/FedoraUnited/repository/raw/master/fedora-enjoy24.rep
```

Website: https://unitedrpms.github.io/

**Comment by kuboosoft** [comment]
why not rename fedora-enjoy24.repo to unitedrpms.repo?

**Comment by paulcarroty** [comment]
@kuboosoft, yeah, good idea.

**Comment by paulcarroty** [comment]
@kuboosoft renamed - https://unitedrpms.github.io/

Please update your G+ group and close this issue.

**Comment by kuboosoft** [comment]
@paulcarroty updated: 05/02/2016...

**Comment by paulcarroty** [comment]
@kuboosoft links that you fixed in G+ groups is broken and give 404. Check website and fix it - https://unitedrpms.github.io/
