### ISSUE TITLE
debuginfo packages 

### ISSUE THREAD

**Issue by sergiomb2** [UnitedRPMs/packages#18]
Hi, 
Lets separate debuginfo packages like in /etc/yum.repos.d/fedora.repo we got a fedora-debuginfo repo

to unitedrpms.repo we just need add :
[unitedrpms-debuginfo]
name=unitedrpms - Debuginfo
baseurl=https://googledrive.com/host/0ByOofIMiUfxPSG00M3hVRHVmYUE/$basearch/debug
#baseurl=https://gitlab.com/FedoraUnited/repository/raw/master/$basearch/debug
enabled=0
skip_if_unavailable=1
gpgcheck=0

```
mkdir x86_64/debug
move x86_64/*debuginfo* x86_64/debug 
cd x86_64/debug
createrepo_c . 
```

**Comment by paulcarroty** [comment]
Good, someone should do it in next package adding: mp3split, rebuilded obs-studio and ffmpeg.

**Comment by paulcarroty** [comment]
I wrote a simply script to automate it.

**Comment by sergiomb2** [comment]
I also added my scripts :
https://gitlab.com/FedoraUnited/repository/blob/master/hist_setup.txt
https://gitlab.com/FedoraUnited/repository/blob/master/hist_sync.txt
