### ISSUE TITLE
strange .html files in repos 

### ISSUE THREAD

**Issue by sergiomb2** [UnitedRPMs/packages#19]
hi,
@paulcarroty , what for are these files https://gitlab.com/FedoraUnited/repository/raw/master, /srpm.html and https://gitlab.com/FedoraUnited/repository/raw/master/index.html , this broke gdrive repo, Removing it , all just work correctly , index.html looks exactly  the same of https://googledrive.com/host/0ByOofIMiUfxPSG00M3hVRHVmYUE/ but this index.html is static and old (not updated) , Google give: ![](http://i.imgur.com/BWpCNl0.png) 
like https://github.com/UnitedRPMs/packages/issues/7 .
So may I rm these fake html pages , that breaks 
`git rm index.html srpm.html x86_64.html `

**Comment by paulcarroty** [comment]
It's probably because I run the repoview on repo root directory.
