### ISSUE TITLE
libva-intel-driver.i686

### ISSUE THREAD

**Issue by lsde** [UnitedRPMs/packages#21]
What about building i686 counterpart to this package for Steam to work?

**Comment by paulcarroty** [comment]
@sergiomb2

**Comment by sergiomb2** [comment]
yes , yes

**Comment by paulcarroty** [comment]
[Temporary solution](https://copr.fedorainfracloud.org/coprs/paulcarroty/libva-intel-driver/build/203742/)

**Comment by sergiomb2** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=770371#c8 
or thing get changed since 2012 or you *can't* build this on copr . 

done in https://github.com/UnitedRPMs/libva-intel-driver/releases/tag/1.7.0-1 , @paulcarroty you upload it ? 
have we more packages to update ?

**Comment by paulcarroty** [comment]
@sergiomb2, I think tomorrow and together with `mp3splt`.

**Comment by sergiomb2** [comment]
do you build the packages ? is what you mean ? I'm a little busy

**Comment by paulcarroty** [comment]
Packages are ready, I need just publish it.

**Comment by sergiomb2** [comment]
I'm going upload it now , with openshot packages ok ? 
@kuboosoft have you things to upload ?

**Comment by sergiomb2** [comment]
updated !

**Comment by lsde** [comment]
good jod and thanks!
