### ISSUE TITLE
Lack of GPG check

### ISSUE THREAD

**Issue by mmcnutt** [UnitedRPMs/packages#22]
If you guys want to be taken seriously by the Fedora community you should probably be enacting GPGcheck on your repos

**Comment by paulcarroty** [comment]
@mmcnutt GPG signing is planned, but impossible in this moment. All our repositories is available only over HTTPS and Big Brother can't harm your OS.

**Comment by kuboosoft** [comment]
@mmcnutt Do not worry, it's a matter of time. We are open if you want to provide infrastructure ;)

**Comment by paulcarroty** [comment]
#29
