### ISSUE TITLE
Marketing | What people says about us

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#24]
- [reddit](https://www.reddit.com/r/linux/comments/4j2q4c/unitedrpms_rpmfusion_alternative_for_fedora_2425/)
- [lor](https://www.linux.org.ru/news/linux-general/12591529)
- [fedoraforum](http://www.forums.fedoraforum.org/showthread.php?p=1761526#post1761526)

Major problems according to comments:
- no gpg sign
- Google Drive isn't a seriously hosting (some people can donate us after leaving :smile: )
- public Koji/Copr
- freetype with subpixel rendering (added to TODO)

@sergiomb2 @kuboosoft

**Comment by kuboosoft** [comment]
GPG sign good idea (We can even sign the repository); but the key are a problem if we changing constantly... 

For all users fedora, all hosting are bad ... we can not give honey for all (experience with other projects) ... is the unique infrastructure; the user takes, drop, or contributes, a best infrastructure is not free...

Koji/Copr (infrastructure=money=know how to do this.)

freetype??

**Comment by sergiomb2** [comment]
> Google Drive isn't a seriously hosting

I can say that , because is very slow upload the sources , but don't see why end user thinks is not serious , have we any argument

**Comment by paulcarroty** [comment]
> infrastructure=money=know how to do this.

I have some **_ideas,_** but need time (1-2 weeks) for personal experiments.

> freetype??

https://en.wikipedia.org/wiki/Subpixel_rendering

> but don't see why end user thinks is not serious , they have any argument ?

Maybe 'serious' projects must have a personal server and costly SSL certificate, I guess.

**Comment by kuboosoft** [comment]
@sergiomb2 nothing; they haven't any valid argument, [read here](https://plus.google.com/104617077706179713070/posts/45gVBMZRgLa)

@paulcarroty google works fine; I can say any kind of infrastructure is welcome, example: I am criticized because I use sourceforge (other project), but they are friendly to my project and  provide a beatiful and enviable infraestructure; which other places it can cost me a lot of money; then google welcome.  in my country you earn little money, and life is hard.

**Comment by leigh123linux** [comment]
Hi

https://github.com/UnitedRPMs/packages/pull/25

**Comment by paulcarroty** [comment]
@kuboosoft OK, I think today we have the maximum for free infrastructure. Of course, this isn't the end, we need more. About monetization/builder/servers we'll talk later.

> I use sourceforge (other project)
Bro, this is your choice. I can't trust company which theft account from their users. It's deliriously. If anyone of you will fing the good and fast storage for mirror - please let me know.

> in my country you earn little money, and life is hard.
Yep, I was googled about your country ( :smile:  ) and know what is the hard life. But it's another motivation to get better.

What we can do easy from these suggestions?

* gpg sign ([it's easy](https://gist.github.com/fernandoaleman/1376720))
* freetype (#24)

**Comment by kuboosoft** [comment]
> I can't trust company which theft account from their users.

mmm then Is your personal opinion also as google. Well; you trust in other places? hahaha, sure? funny... I will give a installer.exe for my project hahaha. man! 

gpg sign; is a question, if @sergiomb2 wants sign all rpm... for me this task is irrelevant and paranoid... easy have problems,  if we changing constantly the sign. But is welcome.

**Comment by paulcarroty** [comment]
@kuboosoft 

> mmm then Is your personal opinion also as google

hahahahahah :smiley_cat: 

[Sourceforge is STILL distributing spyware which tracks your Internet activity from their fake Nmap Project page](https://www.reddit.com/r/linux/comments/3988gb/sourceforge_is_still_distributing_spyware_which/?ref=search_posts)

[Goodbye, Sourceforge!](https://www.reddit.com/r/linux/comments/37til2/goodbye_sourceforge/?ref=search_posts)

[Dying project hosting site Sourceforge hijacks the Nmap account](https://www.reddit.com/r/linux/comments/38ccf2/dying_project_hosting_site_sourceforge_hijacks/?ref=search_posts)

[SourceForge Hijacking Project Accounts [GIMP]](https://www.reddit.com/r/linux/comments/37h4x5/sourceforge_hijacking_project_accounts_gimp/?ref=search_posts)

[GIMP flees SourceForge over dodgy ads and installer](https://www.reddit.com/r/linux/comments/1q6nce/gimp_flees_sourceforge_over_dodgy_ads_and/?ref=search_posts)

@sergiomb2 What you think about GPG sign? My opinion if people need it and it's better for security - we should do it. Just add one line in our script isn't too hard.

**Comment by kuboosoft** [comment]
@paulcarroty your [solid source reddit](https://www.reddit.com/help/privacypolicy) haha

Why you not provide a better choice; each service gives the same crap about your privacy. How maintain a project of this magnitude; with 430,000 projects?;  and you crying here, for a best infraestructure haha; without help of sergio, the repo doesn't exist.. he pays for it... Why you don't pay a "secure"place ;P

**Comment by paulcarroty** [comment]
@kuboosoft OK, you're extreme, I'm understand :-)  I respect your decision, but I do not want to lose the project in a single day.

> without help of sergio, the repo doesn't exist.. he pays for it

@sergiomb2 it's true?

**Comment by sergiomb2** [comment]
> 
> 
>     without help of sergio, the repo doesn't exist.. he pays for it
> 
> @sergiomb2 it's true?

No I do not pay for google drive , I use my personal account , that is why I don't give you access , also have there personal stuff ... 
How sign I can sign all packages no problem . 
About sourceforge , that new have 11 months , sourceforge change the owner , was bought by one group that looks like it really cares about open and free (as freedom) software , and they announce as one of first actions remove adware ....  

But why not create one google account and gpg key for unitedRPMS ? , instead use my gpg . 
Anyway RPMFusion is close to be back 
Best regards.

**Comment by kuboosoft** [comment]
@sergiomb2 yes, here a screenshot when you upload a file via web...
![Image of sourceforge](http://s32.postimg.org/8bbam7uvp/source.png)

**Comment by paulcarroty** [comment]
> But why not create one google account and gpg key for unitedRPMS ? , instead use my gpg .

 Sure. And email.

How to sign packages - https://gist.github.com/fernandoaleman/1376720

> without expiration

It's the very bad idea. 

> Anyway RPMFusion is close to be back 

Great, we need the competition.

**Comment by kuboosoft** [comment]
@paulcarroty  you will give me the reason; and the people will write us each moment about how to import the new key in each change... beautiful.. or problems with updates...

**Comment by paulcarroty** [comment]
@kuboosoft 

> and the people will write us each moment about how to import the new key in each change

Key can't stay forever the same, you can read about it in each cryptography book. Security is especially important while we don't have full access to our repositories.

**Comment by kuboosoft** [comment]
Then, you want a full access to repository? t is your discomfort? why you don't make a mirror with your own google account...

**Comment by sergiomb2** [comment]
>     Anyway RPMFusion is close to be back
> 
> Great, we need the competition.

The current ETA for RPMFusion is F24 GA (General available) by fedora https://fedoraproject.org/wiki/Releases/24/Schedule 2016-06-14 .

But I am thinking was , @kuboosoft could bring postinstallerf to here and we help him to have a better postinstallerf, this UnitedRpms will be an extension, or more bleeding edge technology of Fedora and RPMFusion. 
We don't need follow package guidelines, we can bundle source, build with downloads from internet and allow huge hacks on rpms , also don't care about other rules ...
I'd like emphasize that even so, when we decide update one package that already exist on Fedora or RPMFusion (don't forget look on package reviews bugzilla tickets) we should, IMO, use the same source and open tickets to ask updates on base repos , if we don't have answer, we may package it, if package get updated even better all people will have the update and we don't need to package it!. 
As RPMFusion Administrator, proven packager etc , sooner or later I can update any package, I will not overlap package maintainers , so I hope you @paulcarroty  and @kuboosoft help on update RPMFusion and also Fedora proper. 

Thanks in advance :-)

**Comment by sergiomb2** [comment]
Anyway I need to work in rfpkg , so I will be more or less away

**Comment by paulcarroty** [comment]
> But I am thinking was , @kuboosoft could bring postinstallerf to here and we help him to have a better postinstallerf, this UnitedRpms will be an extension, or more bleeding edge technology of Fedora and RPMFusion. 

Yep,  we could make the same repo with postinstallerf. But it must be the @kuboosoft 's decision.

> We don't need follow package guidelines, we can bundle source, build with downloads from internet and allow huge hacks on rpms , also don't care about other rules ...

Agreed. One our rules is the stable and working solutions. We need it and users need it.

About RPM Fusion: I don't see any sense to help a project which is non interested for our goals: unstable releases. But all specs is open: RPMF can use our, and we can use their specs. 

Our repo is for extreme users (like @kuboosoft :smile: ) that can't wait.

Thanks all.

**Comment by kuboosoft** [comment]
why not; the idea of project postinstallerf was a easy simple way, to install things, for humans, listen a mp3, see a movie edit a video, convert a video for people without knowledge; The necessity forced me to pack rpm ( a Tablet Genius GpenF350).  Usually my github project is updated constantly, as part of project it has your own system-metadata (45325 (included sub-packages) well,  Fedora have this number of rpms; compared to Ubuntu have 60000 aprox without ppa hahaha. Well a part about the history of PostInstallerF. 

@paulcarroty bla Iam not extreme; The people in rawhide want obtain the best experiencie. Ironic but I am not move in rawhide constantly.

Well why not the next level with unitedrpms, we can administer the repository here, and have various mirrors here, the unique problem; if is detected as content unreadable we need open a ticket and explain the project only have content for linux (rpm, and sources) :) and no abuse with it.

https://sourceforge.net/projects/unitedrpms/

**Comment by paulcarroty** [comment]
@kuboosoft YES or NO? The infrastructure problems is minor now.

**Comment by sergiomb2** [comment]
I read Yes , but I'm busy can't read all with attention . I will read it later.

**Comment by kuboosoft** [comment]
@sergiomb2 Rpmfusion people can take our .spec and sources here updated; here all is for all;  We prefer to work neutrally ;)

PostInstallerF have different purposes; and also the project wants love in other distros, actually works with 80% in Ubuntu, Mint; Arch Linux/Manjaro, Theoretically in openSuse

 ... the future migrate to npm+nodejs+..? we can speak to the installer, example "hi post! install all codecs"

**Comment by paulcarroty** [comment]
@kuboosoft: we'll make the one repo for F24 together? Sorry, I can't parse your posts.

**Comment by paulcarroty** [comment]
P.S. Renewed [list](https://github.com/UnitedRPMs/packages/issues/13#issue-151820255) of software for including to URPMS.

**Comment by kuboosoft** [comment]
@paulcarroty only for beta and freeze when rpmfusion is ready; I can't see diferencies betwen f24/25 in this moment... to excepcion of gcc 6.1

**Comment by paulcarroty** [comment]
@kuboosoft https://sourceforge.net/u/paulcarroty/profile/

**Comment by kuboosoft** [comment]
Hey! various people love UnitedRPMs in Ask Fedora :)

**Comment by paulcarroty** [comment]
@kuboosoft it's great, we need many fans to be a number one.
