### ISSUE TITLE
Migration to Git LFS

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#26]
I'm now testing the Git LFS on our [packages](https://github.com/UnitedRPMs/packages) repository.

[Why LFS is better and how to install](https://git-lfs.github.com/)

Gitlab also support LFS and I think we also need to switch the second package mirror. What you think @sergiomb2 @kuboosoft ?

P.S. IMHO we need the package for F24 :smile:

**Comment by sergiomb2** [comment]
if you can put there the repo it will be fantastic

**Comment by kuboosoft** [comment]
great, sounds fine :+1:

**Comment by paulcarroty** [comment]
Nope :cry: Gitlab have a 500 MB limit to LFS.
