### ISSUE TITLE
Remove json06, json07, libcec plataform2.1 , libcdio and fglibc222 rom repos , what do you think ?

### ISSUE THREAD

**Issue by sergiomb2** [UnitedRPMs/packages#27]
hello , I'd like rebuild and republish kodi-pvr , with correct jsoncpp (the one from Fedora proper with hackings) UnitedRPMs/platform-compat#1 ,
Also if you agree remove json06 and json07 from repos , what do you think ?

**Comment by sergiomb2** [comment]
and glibc222-2.22-1.fc24.x86_64.rpm   can I remove it ? 
for now 

        deleted:    jsoncpp07-0.7.0-1.fc24.x86_64.rpm
        deleted:    jsoncpp07-devel-0.7.0-1.fc24.x86_64.rpm
        deleted:    libcdio-0.93-2.fc24.x86_64.rpm
        deleted:    libcdio-devel-0.93-2.fc24.x86_64.rpm
        deleted:    libcec-3.0.1-4.20160330git3a41957.fc24.x86_64.rpm
        deleted:    libcec-devel-3.0.1-4.20160330git3a41957.fc24.x86_64.rpm
        deleted:    platform-2.0.1-1.20160305gitb31c75a.fc24.x86_64.rpm
        deleted:    platform-devel-2.0.1-1.20160305gitb31c75a.fc24.x86_64.rpm
        deleted:    xine-lib-1.2.6-8.fc24.x86_64.rpm
        deleted:    xine-lib-devel-1.2.6-8.fc24.x86_64.rpm
        deleted:    xine-lib-extras-1.2.6-8.fc24.x86_64.rpm

**Comment by kuboosoft** [comment]
* For compatibility no delete platform-compat.
* Delete json06 and json07; no problem if we have hack for jsoncpp :)
* glibc222, isn't necessary I only use this rpm for testing purposes :package: 
* libcec, plataform2.1, libcdio delete; if Fedora provides a updated package:)

**Comment by paulcarroty** [comment]
Great, do it.

**Comment by sergiomb2** [comment]
> For compatibility no delete platform-compat.

I can't find it `ls *compat*` 
just compat-libgcrypt 
anyway I'm writing because I found that fedora already have compat-gcc :) 
https://apps.fedoraproject.org/packages/s/compat-gcc
compat-gcc is an idea that could help me to solve what I called mummify packages :)

**Comment by kuboosoft** [comment]
compat-gcc is a version very old  :/

**Comment by paulcarroty** [comment]
> compat-gcc is a version very old :/

Just create compat-gccXYZ.

**Comment by kuboosoft** [comment]
@paulcarroty as I said here "note" https://copr.fedorainfracloud.org/coprs/davidva/gcc49/ sorry ;)
