### ISSUE TITLE
what happened to https://gitlab.com/FedoraUnited/repository  ? 

### ISSUE THREAD

**Issue by sergiomb2** [UnitedRPMs/packages#28]
I see 
cat repository.gitlab2/srpm/libmng-2.0.3-1.fc24.src.rpm 
version https://git-lfs.github.com/spec/v1
oid sha256:aaf07abfdc483471d95fbd7c4923277957ffbc3141c21c321970f1c4cc0eb20c
size 1551466

What should I do ? , how I get the content  ?

**Comment by paulcarroty** [comment]
After fail with git lfs, I switch again to classical mode and can'd download some packages. Deleting repo and create it again; new repo - the same. 

New problem - [infinite pending](https://www.google.com.ua/search?q=gitlab+build+pending).

**Comment by paulcarroty** [comment]
Fixed.

**Comment by sergiomb2** [comment]
ah we just need run git lfs ?

**Comment by paulcarroty** [comment]
@sergiomb2 forget about LFS. It works shitty with Gitlab.

**Comment by sergiomb2** [comment]
use LFS in github with github, as one mirror , makes sense . Of course not working correctly in gitlab is not a surprise

**Comment by sergiomb2** [comment]
```
du -sh srpm/
```
467M    srpm/
```
du -sh x86_64/
```

512M    x86_64/

now we need almost 1 GB , in future you should need more

**Comment by paulcarroty** [comment]
@sergiomb2 

> use LFS in github with github, as one mirror , makes sense 

One in `packages` repository. I srpms will more than 1 GB, we can use GH releases. Or something else. 

So, I'm surprised, but our "RPM hosting" good very good and fast.
