### ISSUE TITLE
GPG sing - start of process

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#29]
We was discuss later about it, and now can do it. Manuals: [1](https://gist.github.com/fernandoaleman/1376720), [2](https://access.redhat.com/blogs/766093/posts/1976693).

What we need:

1. private and public keys (for all founders)
2. private & secure chat for previous steps
3. public email (I suggest [protonmail](https://protonmail.com/))
4. verification `who is who` (I suggest a video chat) for keysign party
5. rewrite our scripts for automation

**Comment by kuboosoft** [comment]
here only we need somebody make a public and private key; give us via email (with the pass); next, we import it, and solved...   

In other project, I usually sign my packages even the repository (repomd.xml.asc) for those whiners, paranoids, but don't like, ironic because if somebody want harm others users he/she does at all costs  read about [Linux Mint](http://blog.linuxmint.com/?p=2994). Nothing is safe. Meanwhile Ubuntu will change to a different model with "Snappy" packages; I would like to see the whiners here too; It is very easy to include anything there ;)

**Comment by paulcarroty** [comment]
> (with the pass);

I don't think that we need key with pass-phrase 'cause type it for each package is stupid.  

> give us via email

No, I'll don't present our keys for any email service, except protonmail.

**Comment by kuboosoft** [comment]
@paulcarroty why not, then is stupid a GPG key (What it is the purpose for you of a GPG key)... anybody can use my gpg key without permit (I can't take that risk).  I don't recommend mixes or multiples  GPG keys, is a serious problem, and a confusion for the user. Please read it http://www.rpm.org/max-rpm/ch-rpm-pgp.html

**Comment by paulcarroty** [comment]
> I don't recommend mixes or multiples GPG

@kuboosoft I need your and @sergiomb2 *public* keys **for share the UnitedRPMs private key**.

**Comment by sergiomb2** [comment]
How and for where I send it ?

**Comment by paulcarroty** [comment]
@sergiomb2 generate your key as described [here](http://www.rpm.org/max-rpm/ch-rpm-pgp.html), import your **public** key and post it here.

**Comment by sergiomb2** [comment]
our page (pgp.html)  is very confusing is gpg key or pgp key ?!

**Comment by paulcarroty** [comment]
> is gpg key or pgp key ?!
gpg (GNU PG). PGP is't a commercial realization.

```
[paul@probook ~]$ gpg --recv-keys 3A7153DB
gpg: no keyserver known (use option --keyserver)
gpg: keyserver receive failed: bad URI
```

Import your key to any public server.

**Comment by sergiomb2** [comment]
I think you have to configure your default keyserver [1] 
here is my pub key https://pgp.mit.edu/pks/lookup?search=Sergio+Basto&op=index

[1] cat ~/.gnupg/gpg.conf
```
###+++--- GPGConf ---+++###
utf8-strings
#keyserver hkp://keys.gnupg.net
keyserver hkp://pgp.surfnet.nl:11371
```

**Comment by kuboosoft** [comment]
@sergiomb2 then is a pgp? 

@paulcarroty I don't understand why you need various keys?

**Comment by paulcarroty** [comment]
@kuboosoft we need a public GPG keys because we must exchange some confidential information: keys, passwords, certs for infrastructure etc. GPG is the most secure way.

> private hangouts chat... freenode...

Not fully trusted; and remember we have 9+ hours difference in time-zones.

**Comment by paulcarroty** [comment]
@sergiomb2 here's the private data signed with your key. Delete second `.zip` extension, decrypt it and save.
[URPMS_data.zip.gpg.zip](https://github.com/UnitedRPMs/packages/files/275412/URPMS_data.zip.gpg.zip)
 
@kuboosoft I'm waiting for your key. 

After we all have the URPMS keys repo will be signed.

Good weekend. 

P.S. RPMFusion now have a [koji](http://koji.rpmfusion.org/koji/), I'm probably add some new packages before signing.

**Comment by kuboosoft** [comment]
@paulcarroty tomorrow, I will create a new key... I haven't my pc with Fedora in this moment hahha; Good weekend.

**Comment by sergiomb2** [comment]
@paulcarroty cool !
```
gpg2 --import URPMS-GPG-PRIVKEY-Fedora-24 
gpg2 --import URPMS-GPG-PUBLICKEY-Fedora-24 
```
cat ~/.rpmmacros
```
%packager       The UnitedRPMs Project (Key for UnitedRPMs infrastructure) <unitedrpms@protonmail.com>
%vendor         UnitedRPMs
%_signature     gpg
%_gpg_name      The UnitedRPMs Project
```

and I already had sign all packages with `rpm --addsign *.rpm` , I'm  commit it now in repo should take some time ... 

I need add pubkey  to internet , update .repo files with URL of pubkey  ...

**Comment by paulcarroty** [comment]
@sergiomb2 great. All our `.repo` now are the same and support mirrors. #30

**Comment by paulcarroty** [comment]
@sergiomb2 gpg check and mirroring is now enable in all confings.

**Comment by valmar** [comment]
Currently the signature check is enabled in the repo file, but the pubkey URL is not in the file. As it is, no package can be installed. (Except by turning off the signature check manually)

**Comment by paulcarroty** [comment]
@valmar fixed.

**Comment by sergiomb2** [comment]
man the fix is not disable gpgcheck !!!! , is import gpgkey

**Comment by paulcarroty** [comment]
@sergiomb2 sign instruction added to website, check it: https://unitedrpms.github.io/

All packages in all mirrors is signed?

**Comment by valmar** [comment]
It seems not to be working. I have imported the keys as described on the website, turned on the gpg check  in the repo file, then I tried to install freetype-freeworld. Got this:

sudo dnf install freetype-freeworld
Last metadata expiration check: 2:48:27 ago on Mon May 23 11:18:20 2016.
Dependencies resolved.
=====================================================================================
 Package                   Arch          Version             Repository         Size
=====================================================================================
Reinstalling:
 freetype-freeworld        x86_64        2.6.3-1.fc24        unitedrpms        401 k

Transaction Summary
=====================================================================================

Total download size: 401 k
Is this ok [y/N]: y
Downloading Packages:
freetype-freeworld-2.6.3-1.fc24.x86_64.rpm           167 kB/s | 401 kB     00:02    
-------------------------------------------------------------------------------------
Total                                                137 kB/s | 401 kB     00:02     
warning: /var/cache/dnf/unitedrpms-0ea796365f99dbac/packages/freetype-freeworld-2.6.3-1.fc24.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 5250aef3: NOKEY
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Public key for freetype-freeworld-2.6.3-1.fc24.x86_64.rpm is not installed

**Comment by paulcarroty** [comment]
@valmar big thx for your help. You really have installed our public key? Check it:

```
$ gpg2 --list-keys
```

So, I'm was resigned all packages in our Gitlab mirror. It works:

```
$ rpm --resign *rpm
```

```
$ cat /etc/yum.repos.d/unitedrpms.repo 

name=unitedrpms
baseurl=https://gitlab.com/FedoraUnited/repository/raw/master/x86_64/
enabled=1
skip_if_unavailable=1
gpgcheck=1
gpgkey=https://raw.githubusercontent.com/UnitedRPMs/unitedrpms.github.io/master/URPMS-GPG-PUBLICKEY-Fedora-24

[unitedrpms-source]
name=unitedrpms - Source
baseurl=https://gitlab.com/FedoraUnited/repository/raw/master/x86_64/debug/
#mirrorlist=https://unitedrpms.github.io/mirrorlist_enjoy24_source.txt
enabled=0
skip_if_unavailable=1
gpgcheck=1
gpgkey=https://raw.githubusercontent.com/UnitedRPMs/unitedrpms.github.io/master/URPMS-GPG-PUBLICKEY-Fedora-24


[unitedrpms-debuginfo]
name=unitedrpms - Debuginfo
baseurl=https://gitlab.com/FedoraUnited/repository/raw/master/srpm/
enabled=0
skip_if_unavailable=1
gpgcheck=1
gpgkey=https://raw.githubusercontent.com/UnitedRPMs/unitedrpms.github.io/master/URPMS-GPG-PUBLICKEY-Fedora-24
```

Wait for @sergiomb2 sync and enable GPG check synchronously for all mirrors.

**Comment by valmar** [comment]
No problem. Thank you for providing this repo! 

You were right. I don't know how this could happen, but the import of the key failed. Now I reimported it and everything works.

If you put the gpgkey entry in the repo file, however, I think people do not need to import the key manually, so I would update the repo file installed by configmanager as soon as possible!

Thank you again!

Valerio

**Comment by paulcarroty** [comment]
@valmar you're welcome.

> If you put the gpgkey entry in the repo file, however, I think people do not need to import the key manually,

We'll probably do in near future.

**Comment by sergiomb2** [comment]
> 
> 
> @valmar you're welcome.
> 
>     If you put the gpgkey entry in the repo file, however, I think people do not need to import the key manually,
> 
> We'll probably do in near future.

yes , that is I'm trying to do , and it should be done now :smiley: 
@paulcarroty  yes all packages (from yesterday, I haven't check today ) , are signed and sync 

we maybe should do: reinstall .repo file and 

`dnf distro-sync `

I'm in a area with internet limitations ...

**Comment by sergiomb2** [comment]
https://github.com/contact

Updated 23 minutes ago: Some users may experience a delay in pushes or other changes appearing on the site.

That is my case, please wait !!!

**Comment by kuboosoft** [comment]
@sergiomb2 @paulcarroty  

> Updated 38 minutes ago: Some users may experience a delay in pushes or other changes appearing on the site.

**Comment by paulcarroty** [comment]
GPG checking in enabled for all repos. 

@kuboosoft please tell it for G+ folks.

**Comment by sergiomb2** [comment]
> GPG checking in enabled for all repos.

```
Files unitedrpms.github.io/fedora-enjoy24.repo and repository.gitlab/fedora-enjoy24.repo differ
Files unitedrpms.github.io/mirrorlist_enjoy24_debug.txt and repository.gitlab/mirrorlist_enjoy24_debug.txt differ
Files unitedrpms.github.io/mirrorlist_enjoy24_source.txt and repository.gitlab/mirrorlist_enjoy24_source.txt differ
Files unitedrpms.github.io/mirrorlist_enjoy24_x86_64.txt and repository.gitlab/mirrorlist_enjoy24_x86_64.txt differ
Files unitedrpms.github.io/unitedrpms.repo and repository.gitlab/unitedrpms.repo differ
```

Shouldn't we haven't repo and mirror list only in one place , well at least they should be equal ! 
I think @paulcarroty swap mirror in repository of gitlab but not in website (unitedrpms.github.io) ,
I going update website with latest repos , mirror seems to me that it only used the website information ... 

for me the official config is (the g+ info) :  
#dnf config-manager --add-repo=https://unitedrpms.github.io/fedora-enjoy24.repo

**Comment by paulcarroty** [comment]
@sergiomb2 +, I see you was fix it.

@kuboosoft please change `fedora-enjoy24.repo` to `unitedrpms.repo` and we'll delete the legacy.

**Comment by sergiomb2** [comment]
> @kuboosoft please change fedora-enjoy24.repo to unitedrpms.repo in G+ and we'll delete the legacy.   

@kuboosoft  your post update is incomplete you wrote:  # dnf config-manager --add-repo=https://unitedrpms.github.io/unitedrpm﻿
when it is  dnf config-manager --add-repo=https://unitedrpms.github.io/unitedrpms.repo  !!!

**Comment by kuboosoft** [comment]
hahaha; maybe I was slept; updated :)

**Comment by sergiomb2** [comment]
> Shouldn't we haven't repo and mirror list only in one place , well at least they should be equal ! 

fix in https://gitlab.com/FedoraUnited/repository/commit/d8b1d9ac0ec92f66632f6704101c31b39289876d

anyway this issue isn't done ? may we close it ?

**Comment by paulcarroty** [comment]
Closed because we have implemented all planned tasks.
