### ISSUE TITLE
The one and only unified .repo config

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#30]
As described [here](https://fedoraproject.org/wiki/Infrastructure/MirrorManager?rd=MirrorManager#Metalink_format_mirrorlist), we can do something like 

```
metalink=URL1
metalink=URL2
```

or
```
mirrorlist=URL1
mirrorlist=URL2
mirrorlist=URLn
```

Your minds?

**Comment by sergiomb2** [comment]
Before we should do one package called: unitedrpms-release  
which contains gpg and repo files,  something like :  /etc/pki/rpm-gpg/RPM-GPG-KEY-unitedrpms and /etc/yum.repos.d/unitedrpms.repo
second we need have a mirror or metalink site  ... (thinking on that should be easy)

**Comment by paulcarroty** [comment]
> second we need have a mirror or metalink site ... (thinking on that should be easy)

we can just use `mirrorlist`. 

> which contains gpg

I'm ready for signing and wait for you. #29

**Comment by kuboosoft** [comment]
@sergiomb2 easy , here in github../GPG/2?/RPM-GPG-KEY-unitedrpms 
@paulcarroty . What key you will use?

**Comment by paulcarroty** [comment]
Done, all our `.repo` configs is now the same.

**Comment by paulcarroty** [comment]
Doesn't work, dnf can't handle the second repo from `mirrorlist=url`.

**Comment by sergiomb2** [comment]
rm /etc/yum.repos.d/fedora-enjoy24.repo 

`dnf config-manager --add-repo=https://unitedrpms.github.io/fedora-enjoy24.repo ` (note is the instructions on g+ post ) 

and is working for me , now just need update .repo files in the others place 

err not yet need add gpgkey=https://copr-be.cloud.fedoraproject.org/results/etc  
tomorrow

**Comment by paulcarroty** [comment]
@sergiomb2 great, it works!

**Comment by kuboosoft** [comment]
> https://gitlab.com/FedoraUnited/repository/raw/master/x86_64/ error 404??
remember a git service as github/gitlab doesn't work as dedicated host service; different history with source forge ;) try change to https://gitlab.com/FedoraUnited/repository/tree/master/x86_64/

**Comment by paulcarroty** [comment]
> error 404??

@kuboosoft, you doesn't have access to directory, just to files:

```
# dnf download mpv
Last metadata expiration check: 3:55:56 ago on Mon May 23 16:59:28 2016.
mpv-0.17.0-2.fc24.x86_64.rpm                                                    386 kB/s | 981 kB     00:02    
[root@probook ~]# 

```

I use the only Gitlab mirror.

**Comment by paulcarroty** [comment]
So, thankful to @sergiomb2 we now have the united repo config and this issue can be closed.
