### ISSUE TITLE
The one repo with Postinstallerf: packages for including

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#31]
https://sourceforge.net/projects/postinstaller/files/fedora/releases/24/SRPM/

I recommend to create a list and use @kuboosoft's scripts for automation.

**Comment by sergiomb2** [comment]
why this is closed ?

**Comment by paulcarroty** [comment]
@sergiomb2 closed as uninterested for everyone.

**Comment by sergiomb2** [comment]
I' m interested , but after F24 GA , RpmFusion rise and up

**Comment by paulcarroty** [comment]
OK, reopen.

**Comment by kuboosoft** [comment]
Why not? haha

**Comment by paulcarroty** [comment]
@kuboosoft your all packages are tested? Built with ffmpeg 2.* I see?
