### ISSUE TITLE
Sourceforge as new repository hosting

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#32]
@kuboosoft [propose](https://github.com/UnitedRPMs/packages/issues/24#issuecomment-220389018) to use Sourceforge as mirror.

I'm not sure technically that we'll get something better that we have now. We theoretically can switch from Google Drive 'cause people hate it. Or use it as 3th mirror for better stability.

@sergiomb2 what you think? Your vote is final.

**Comment by kuboosoft** [comment]
3 mirrors sounds great :)

**Comment by paulcarroty** [comment]
@kuboosoft https://www.youtube.com/watch?v=ZXsQAXx_ao0 :)

**Comment by sergiomb2** [comment]
why not :smile: ?

**Comment by kuboosoft** [comment]
Source Forge only can import from Allura, GitHub, Trac; bad bad
I have a very low internet connection... upload 1.3GB is a problem for me hahaha @paulcarroty 
Steps
1) clone gitlab (1.3)
2) git push (1.3)
------------------------
2.6 GB hahaha; I will died

**Comment by paulcarroty** [comment]
@kuboosoft ok, give me the access to https://sourceforge.net/projects/unitedrpms/

> I have a very low internet connection... upload 1.3GB is a problem for me hahaha

As say Shia: stop giving up!!! :smile: and make it better.

Good news: sourceforge  are supports sftp, ssh, rsync.

> 1.3GB

files + size (git objects = size files) + size (git objects of your old deleted files)

**Comment by sergiomb2** [comment]
> 2.6 GB hahaha; I will died; maybe I will enable when I have time...

I have a good upload , here and now , I may upload it .. but , shouldn't be in git , should be in host , don't you think ?

**Comment by sergiomb2** [comment]
my user is sergimb at sf.net

**Comment by paulcarroty** [comment]
@sergiomb2 

> I have a good upload

In mbps?

> but , shouldn't be in git , should be in host

without `.git` directory you mean?

**Comment by paulcarroty** [comment]
Done: https://sourceforge.net/projects/urpms/ 

You're added as sergiomb.

**Comment by sergiomb2** [comment]
ah , 
but https://sourceforge.net/projects/urpms/ or https://sourceforge.net/projects/unitedrpms/
and look how @kuboosoft  does https://sourceforge.net/projects/unitedrpms/files/fedora/ ... yeah kubo give us access please !

**Comment by sergiomb2** [comment]
> In mbps?

100 Mbps download , 20 Mbps upload

**Comment by paulcarroty** [comment]
I was ask @kuboosoft a lot of times, no sense wait so long.

**Comment by kuboosoft** [comment]
Hi, @sergiomb2 full acces done. Now @paulcarroty

**Comment by kuboosoft** [comment]
script if you want upload (uses rsync); Good night, I am very tired, I need to sleep.
[rsync-unitedrpm.zip](https://github.com/UnitedRPMs/packages/files/283613/rsync-unitedrpm.zip)

**Comment by paulcarroty** [comment]
@kuboosoft sorry and thanks.

**Comment by paulcarroty** [comment]
It works:

```
$ $ rsync -arv --exclude repository/.git/ -e ssh repository/ paulcarroty@frs.sourceforge.net:/home/frs/project/unitedrpms/repository/
```

**Comment by paulcarroty** [comment]
@sergiomb2 mirror is added and enabled and you can disable the Google Drive mirror as you wish.

**Comment by sergiomb2** [comment]
Hello some points : 
Point 1- @paulcarroty can we delete https://sourceforge.net/projects/urpms/ ? we will use projects/unitedrpms/ isn't it ? 
Point 2 - https://sourceforge.net/projects/unitedrpms/files/repository/x86_64/ (Source: README.md, updated 2016-05-03 ) , shouldn't we unify and use :  dnf config-manager --add-repo=https://unitedrpms.github.io/unitedrpms.repo instead dnf config-manager --add-repo=https://gitlab.com/FedoraUnited/repository/raw/master/unitedrpms.repo
Point 3 - have someone test sourceforge mirror ? it always good test it ... ( I hadn't time so far)

**Comment by paulcarroty** [comment]
@sergiomb2 

1 - ticket is created.

2 -  it's better, but we need to create the `urpms-release.rpm`

3 - 

```
$ curl -LO https://sourceforge.net/projects/unitedrpms/files/repository/x86_64/mlt-6.2.0-2.fc24.x86_64.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   391    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   461    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0   375    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100 2400k  100 2400k    0     0   410k      0  0:00:05  0:00:05 --:--:--  656k
[paul@localhost tmp]$ ls

```

**Comment by sergiomb2** [comment]
> rsync-unitedrpm.zip

@kuboosoft thanks , what for ? 

     gpg --detach-sign --armor repodata/repomd.xml

should we do the same ? 

from the script I just did a simply rsync: 

    rsync -av --ignore-existing --delete .  myuser@frs.sourceforge.net:/home/frs/project/unitedrpms/repository/

**Comment by kuboosoft** [comment]
@sergiomb2 This was a request in postinstallerf; various users with high security standards. ; but isn't enabled by default. A double shielding for anyone who wants to activate.

**Comment by paulcarroty** [comment]
@sergiomb2 you have any plans to disable Google Drive mirror?

**Comment by sergiomb2** [comment]
> you have any plans to disable Google Drive mirror?

yes, I want disable Google Drive mirror ... , can you remove it from mirrors , I waste many time try sync it .

**Comment by paulcarroty** [comment]
> can you remove it from mirrors?

Yes, but we have a problem - gitlab and sourceforge can produce the  repoview `index.html` for browser.

Also I think we need something like a blog with hot news with repo updates, new mirrors/packages/hotfixes etc.

**Comment by sergiomb2** [comment]
https://sourceforge.net/p/forge/documentation/Project%20Web%20Services/#quick-start-guide-for-project-web looks good but I hadn't time yet

**Comment by sergiomb2** [comment]
what do you think ? 
http://unitedrpms.sourceforge.net/srpm/repoview/
http://unitedrpms.sourceforge.net/x86_64/repoview/
http://unitedrpms.sourceforge.net/x86_64/debug/repoview/

**Comment by paulcarroty** [comment]
> http://unitedrpms.sourceforge.net/x86_64/repoview/

Added to website.

**Comment by paulcarroty** [comment]
@kuboosoft let's write about disabled Google Drive in G+.

**Comment by sergiomb2** [comment]
@paulcarroty and @kuboosoft with https://gitlab.com/FedoraUnited/repository/blob/c126271fad002ed16095317f5d42f3a42710c2a8/sync_sf_repoviews.sh 
running sync_sf_repoviews.sh update repoviews with latest changes  in http://unitedrpms.sourceforge.net/ .

**Comment by paulcarroty** [comment]
@sergiomb2 `add_packages.sh` do all what we need, just copy new packages to `/tmp/` and run it.

**Comment by sergiomb2** [comment]
we  need add to add_packages.sh  the lines : 
```
rsync -av --delete -e ssh x86_64/repoview/ web.sourceforge.net:/home/project-web/unitedrpms/htdocs/x86_64/repoview/
rsync -av --delete -e ssh x86_64/debug/repoview/ web.sourceforge.net:/home/project-web/unitedrpms/htdocs/x86_64/debug/repoview/
rsync -av --delete -e ssh srpm/repoview/ web.sourceforge.net:/home/project-web/unitedrpms/htdocs/srpm/repoview/
```

**Comment by sergiomb2** [comment]
may I change the add_packages.sh  ? @paulcarroty do you use ssh key to authenticate via ssh ? I'm asking to change the script according  the information .
I have in   ~/.ssh/config : 
```
Host *.sourceforge.net
    User sergiomb
    IdentityFile ~/.ssh/id_rsa
```
I upload my id_rsa.pub to sourceforge.net (need be an rsa , my dsa key not working) 
after I run :  `keychain -q ~/.ssh/id_rsa` and don't enter passwords to run the script

**Comment by paulcarroty** [comment]
@sergiomb2 why not? Just add it. I use the ssh key without any config.

**Comment by kuboosoft** [comment]
> let's write about disabled Google Drive in G+.

Hi, is difficult follow all reports here (maximum if constantly the issues is closed) hahaha; my answer is not, I prefer various mirrors.

@sergiomb2 
Thanks for the script.

@paulcarroty 
:100:

**Comment by paulcarroty** [comment]
> my answer is not, I prefer various mirrors.

Good, let's create your GD mirror and we'll add it. GD is TOOO SLOOOW for upload.

**Comment by sergiomb2** [comment]
> GD is TOOO SLOOOW for upload.

my google drive almost stop, I had 1k of upload via google-drive-ocamlfuse, I found google doesn't delete nothing, so I had in trash thousands of files in trash folder ... Conclusion google-drive-ocamlfuse is not a good solution , for refresh files every day .

**Comment by paulcarroty** [comment]
@sergiomb2 OK, delete all rpms, lets people readd the repo.

**Comment by sergiomb2** [comment]
it is already done , since yesterday ...
