### ISSUE TITLE
Error: nothing provides libvpx.so.3()(64bit) needed by chromium-1:50.0.2661.86-1.fc24.x86_64

### ISSUE THREAD

**Issue by ShadowCreator** [UnitedRPMs/packages#33]
I had a look and rpm -ql  shows that libvpx from the Fedora repo's provides libvpx.so.2 but not libvpx.so.3.

**Comment by paulcarroty** [comment]
Try to install this package: http://koji.fedoraproject.org/koji/buildinfo?buildID=745709 via:

```
# dnf install https://kojipkgs.fedoraproject.org//packages/libvpx/1.5.0/4.fc24/x86_64/libvpx-1.5.0-4.fc24.x86_64.rpm
```

We should wait for rebuild ~5-10 hours. As temporary alternative - [repo](https://copr.fedorainfracloud.org/coprs/lantw44/chromium/).

**Comment by paulcarroty** [comment]
@ShadowCreator please test: https://github.com/UnitedRPMs/chromium/releases/tag/50.0.2661.86-2

**Comment by region51** [comment]
@paulcarroty а почему твой новый пакет 50.0.2661.86-2, показывает
```
[maxim@localhost Documents]$ rpmlint chromedriver-50.0.2661.86-2.fc24.x86_64.rpm
chromedriver.x86_64: W: incoherent-version-in-changelog 50.0.2661.86-1.R ['1:50.0.2661.86-2.fc24', 
'1:50.0.2661.86-2']
```

>50.0.2661.86-1.R

???

**Comment by region51** [comment]
А в chromium-debuginfo другая, узазывает всем известную R.
```
[maxim@localhost Documents]$ rpmlint chromium-debuginfo-50.0.2661.86-2.fc24.x86_64.rpm
chromium-debuginfo.x86_64: W: incoherent-version-in-changelog 50.0.2661.86-2.R ['1:50.0.2661.86-2.fc24', '1:50.0.2661.86-2']

```

**Comment by paulcarroty** [comment]
@region51, 更新日誌是固定的.

**Comment by paulcarroty** [comment]
Rebuild was added to repository.
