### ISSUE TITLE
Any plans for the wireless drivers?

### ISSUE THREAD

**Issue by kmyid** [UnitedRPMs/packages#37]
Hi guys, 

Awesome job you guys are doing :+1: 

Similar to freetype-freeworld, it would be nice if akmods-wl (which would depend on kmodtool, buildsys-build-rpmfusion, akmods) is supported. This would actually make my completely move away from my local repo :-) Do you have any plans for this?

Thanks,
Kwang

**Comment by paulcarroty** [comment]
Hi @kmyid, we'll try to add in future.

So, if you have a repository with tested packages then your pull request will be better.

**Comment by kmyid** [comment]
> So, if you have a repository with tested packages then your pull request will be better.

I just downloaded the current SRPMS for the above packages from rpmfusion and recompiled it. The only modification I did was changing the kernel version to compile to mine. See 

https://github.com/kmyid/buildsys-build-rpmfusion

You can probably for directly from the rpmfusion repos :-)

**Comment by paulcarroty** [comment]
@kmyid it's good, but I don't like the rebuilds after every new kernel version.

Maybe @sergiomb2 or/and @kuboosoft will be interested to create the universal package.

**Comment by kuboosoft** [comment]
@kmyid You can help updating; we can clone your github repository , and you can give to the project,  a grain of sand, updating in each new kernel.

**Comment by sergiomb2** [comment]
https://copr.fedorainfracloud.org/coprs/sergiomb/vboxfor23/monitor/ on epel7 you got what you need to build kmods with akmods in customer box , you just need add kmodtool  and buildsys-build-rpmfusion

**Comment by kmyid** [comment]
> You can help updating; we can clone your github repository , and you can give to the project, a grain of sand, updating in each new kernel.

I am not really familiar with how these things are done, so it's a bit daunting for me at the moment :-(

**Comment by paulcarroty** [comment]
DKMS is the best way.

**Comment by sergiomb2** [comment]
I prefer akmods just because already works on RpmFusion F23 , we just need fork [1] 
https://github.com/rpmfusion/broadcom-wl
https://github.com/rpmfusion/wl-kmod

on https://github.com/rpmfusion/wl-kmod/blob/master/wl-kmod.spec we just need use 
`%global buildforkernels akmod `
instead : 
`%global buildforkernels current`

which just build akmod-wl and not depend on kernel or  buildsys-build-rpmfusion
[1] 
https://github.com/rpmfusion/?utf8=%E2%9C%93&query=wl

**Comment by paulcarroty** [comment]
Fork complete, @kmyid added as a collaborator. Let's try to compile, I don't have any hardware from Broadcom.

**Comment by kmyid** [comment]
> Fork complete, @kmyid added as a collaborator. Let's try to compile, I don't have any hardware from Broadcom.

Hi guys, I'll try to do it over the weekend or early next week. I have lot's of thing going on related to work at the moment, consuming all my free time :-(

**Comment by TingPing** [comment]
By the way here is a package for b43-firmware: https://dl.tingping.se/fedora/repoview/b43-firmware.html

**Comment by paulcarroty** [comment]
@TingPing big thanks. Anyone can test this package in action? @kmyid ?

It's precompiled and maybe will have some problems with modern kernel.

**Comment by TingPing** [comment]
The blob is just firmware not a driver or anything.

**Comment by kmyid** [comment]
Me again.

I think since RPM fusion is back up and providing the packages for both 24 and rawhide, the wireless support is not a big deal anymore. I am closing this issue.

**Comment by kuboosoft** [comment]
Well; we had dkms for broadcom working great!
https://github.com/UnitedRPMs/broadcom-wl-dkms
