### ISSUE TITLE
Atom - cant launch from UI (can from commandline)

### ISSUE THREAD

**Issue by abradshaw** [UnitedRPMs/packages#38]
Cant start application from GUI (via desktop file). I guess it may be that the desktop file is from my previous (non-united rpms) install.

UI message says "Failed to launch Atom - Failed to execute child process /usr/share/atom/atom"

Upon doing "which atom"
 $ which atom
  /usr/bin/atom

It runs fine from the command line

**Comment by paulcarroty** [comment]
Try

`# dnf erase atom nodejs-atom-package-manager`
`# dnf install atom nodejs-atom-package-manager`

**Comment by abradshaw** [comment]
Hi Paul

That did the trick - many thanks for the super fast response
