### ISSUE TITLE
Spotify Screen Glitches

### ISSUE THREAD

**Issue by thunderbirdtr** [UnitedRPMs/packages#39]
Package version : spotify-client-1.0.27-1.fc24.x86_64

I installed spotify-client and when I tried to login I saw screen-glitches and have happening randomly. Spotify is working but glitches kinda bugy so I don't know what cause of it. but It's happening all the time. 

https://paste.fedoraproject.org/372823/74904146/

Thank you.

**Comment by paulcarroty** [comment]
Here's the pre-release of nevest version: https://github.com/UnitedRPMs/spotify-client/releases/tag/1.0.28

How to test it:

```
# dnf erase spotify-client
# dnf install https://github.com/UnitedRPMs/spotify-client/releases/download/1.0.28/spotify-client-1.0.28.89.gf959d4ce-1.fc24.noarch.rpm
```

**Comment by thunderbirdtr** [comment]
Well I think It need to be re-package for that :) Because in repository contain 1.5.5 and It's ask for 1.5.4 so It can't be installed without change SRPM and make RPM again. 

`dnf install spotify-client-1.0.28.89.gf959d4ce-1.fc24.noarch.rpm`
`Last metadata expiration check: 1:56:13 ago on Tue May 31 09:10:02 2016.`
`Error: nothing provides libgcrypt1.5.4 needed by spotify-client-1.0.28.89.gf959d4ce-1.fc24.noarch`

Thank you.`

**Comment by paulcarroty** [comment]
@kuboosoft you've added the [package](https://github.com/UnitedRPMs/libgcrypt1.5.4), but not build it :smile:

**Comment by thunderbirdtr** [comment]
Why don't we use 1.5.5 instead of 1.5.4 is it really necessary ? Looks like It accept 1.5.5. so ? and compat-libgcrpyt should do the trick.

**Comment by kuboosoft** [comment]
rm -rf $HOME/.local/share/ 
Now open Spotify
We spotify is only a installer...

**Comment by kuboosoft** [comment]
@thunderbirdtr Spotify only needs "libgcrypt.so*" for me isn't a good idea a complete "compat-libgcrpyt" it can cause conflict with the official libgcrpyt.
@paulcarroty it compile fine [Log](https://da.gd/POjM4 
)

**Comment by thunderbirdtr** [comment]
@kuboosoft  for delete part 

`rm -rf $HOME/.config/spotify`

And for libgcrypt.so* part when we install ; compat-libgcrpyt It provide

```
/etc/gcrypt
/usr/lib64/.libgcrypt.so.11.hmac
/usr/lib64/libgcrypt.so.11
/usr/lib64/libgcrypt.so.11.8.4
/usr/share/doc/compat-libgcrypt
/usr/share/doc/compat-libgcrypt/AUTHORS
/usr/share/doc/compat-libgcrypt/NEWS
/usr/share/doc/compat-libgcrypt/THANKS
/usr/share/licenses/compat-libgcrypt
/usr/share/licenses/compat-libgcrypt/COPYING.LIB

```
This libs is it what we want already for spotify so that is why I asked for 1.5.5 will gonna enough ?

**Comment by kuboosoft** [comment]
@thunderbirdtr I am Sorry, now I am using my pc, and saw your question, you have a version "1.0.27-1" sorry but I haven't a 1.0.27-1 release... I don't found a registry for this release, I do not understand what happened, Our version make symlinks, and imports paths for compatibility, remember spotify is a .deb only for Ubuntu and requires old dependencies.

**Comment by sergiomb2** [comment]
http://repository.spotify.com/pool/non-free/s/spotify-client/

by luck I see that we have new version today !

**Comment by kuboosoft** [comment]
@paulcarroty  @sergiomb2 Updated ;)

**Comment by thunderbirdtr** [comment]
That's broken package too. Now we can't install spotify if I delete old one I have.

```
Dependencies resolved.
================================================================================
 Package           Arch      Version                        Repository     Size
================================================================================
Skipping packages with broken dependencies:
 spotify-client    noarch    1.0.28.89.gf959d4ce-1.fc24     unitedrpms     23 k

Transaction Summary
================================================================================
Skip  1 Package

Nothing to do.
Complete!


```

**Comment by kuboosoft** [comment]
@thunderbirdtr https://github.com/UnitedRPMs/packages/wiki/About-updates

**Comment by thunderbirdtr** [comment]
I did that before update but will check afternoon. I'm sure of it.

**Comment by paulcarroty** [comment]
@kuboosoft you're don't include the rpms of last version into repo and github releases.

**Comment by paulcarroty** [comment]
P.S. 1.0.31.56.g526cfefe-1.fc24 was added to repository, let's test it:

```
# dnf install spotify-client
...
Dependencies resolved.
================================================================================
 Package            Arch   Version                             Repository  Size
================================================================================
Installing:
 dbusmenu-qt        x86_64 0.9.3-0.11.20150604.fc24            rawhide     91 k
 libXaw             x86_64 1.0.13-4.fc25                       rawhide    189 k
 libgcrypt1.5.4     x86_64 1.5.4-4.fc24                        unitedrpms 240 k
 openssl1           x86_64 1.0.0-4.fc24                        unitedrpms 749 k
 proj               x86_64 4.9.2-2.fc24                        rawhide    208 k
 qt                 x86_64 1:4.8.7-17.fc25                     rawhide    4.8 M
 qt-common          noarch 1:4.8.7-17.fc25                     rawhide    8.0 k
 qt-mobility-common x86_64 1.2.2-0.23.20140317git169da60c.fc24 rawhide     40 k
 qt-mobility-location
                    x86_64 1.2.2-0.23.20140317git169da60c.fc24 rawhide    550 k
 qt-mobility-sensors
                    x86_64 1.2.2-0.23.20140317git169da60c.fc24 rawhide    121 k
 qt-settings        noarch 24-6.fc25                           rawhide     25 k
 qt-x11             x86_64 1:4.8.7-17.fc25                     rawhide     12 M
 qtwebkit           x86_64 2.3.4-11.fc24                       rawhide     10 M
 sni-qt             x86_64 0.2.6-7.fc24                        rawhide     58 k
 spotify-client     noarch 1.0.31.56.g526cfefe-1.fc24          unitedrpms  34 k
 systemd-devel      x86_64 230-2.fc25                          rawhide    285 k
 xterm              x86_64 324-1.fc25                          rawhide    505 k

Transaction Summary
================================================================================
Install  17 Packages

Total download size: 30 M
Installed size: 96 M
```

**Comment by thunderbirdtr** [comment]
Yeap It's installed don't have glitches and working fine. Thank you. We can close I think :) :+1:
