### ISSUE TITLE
exfat-utils and fuse-exfat

### ISSUE THREAD

**Issue by kaepora** [UnitedRPMs/packages#43]
I think it would be beneficial to add the packages that provide [exFAT](https://en.wikipedia.org/wiki/ExFAT) support to UnitedRPMs. I can work on making this happen. Are you interested?

Generally with RPMFusion, installing `exfat-utils` and `fuse-exfat` does the job and integrates support into GNOME automatically.

**Comment by sergiomb2** [comment]
Please fork: 
https://github.com/rpmfusion/fuse-exfat and https://github.com/rpmfusion/exfat-utils

**Comment by paulcarroty** [comment]
Fork is done: 
* https://github.com/UnitedRPMs/fuse-exfat
* https://github.com/UnitedRPMs/exfat-utils

@kaepora now have rw access, check invite.

> I can work on making this happen. Are you interested?

We're always interested if someone can help :smile:

**Comment by kaepora** [comment]
You guys are awesome!

**Comment by sergiomb2** [comment]
@paulcarroty  , now may you built it for F24 ?

**Comment by paulcarroty** [comment]
@sergiomb2 done.

**Comment by kuboosoft** [comment]
Welcome @kaepora now make your changes :)

**Comment by kaepora** [comment]
Works great! Will try to maintain in the future :-)

**Comment by paulcarroty** [comment]
@kaepora OK.
