### ISSUE TITLE
Failed to synchronize cache for repo 'unitedrpms', disabling

### ISSUE THREAD

**Issue by mrpg99** [UnitedRPMs/packages#45]
Hi,

I'll log this here instead of using the comments section on the google+ site 

I cannot refresh the repo, or install anything from it anymore 

sudo dnf -y clean all; sudo dnf -y update
0 files removed
slack                                            13 kB/s |  23 kB     00:01    
negativo17 - Steam                              130 kB/s | 7.9 kB     00:00    
Fedora 24 - x86_64 - Updates                    1.6 kB/s | 257  B     00:00    
google-talkplugin                                37 kB/s | 2.7 kB     00:00    
google-chrome                                    47 kB/s | 3.4 kB     00:00    
Opera packages                                   49 kB/s |  12 kB     00:00    
negativo17 - Spotify                             68 kB/s | 3.6 kB     00:00    
Fedora 24 - x86_64                              5.2 MB/s |  47 MB     00:08    
Failed to synchronize cache for repo 'unitedrpms', disabling.
Last metadata expiration check: 0:00:25 ago on Fri Jun 10 16:32:26 2016.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by paulcarroty** [comment]
@mrpg99 not accepted, but speed is very slow:

```
unitedrpms        6.9 kB/s | 542 kB     01:19    
```

Try to delete `unitedrpms.repo`, `fedora-enjoy24.repo` from `/etc/yum.repos.d` and add repo from our website.

P.S. @sergiomb2 @kuboosoft maybe we need to setup sourceforge the first in list?

**Comment by mrpg99** [comment]
Thank you Paul, this sorted it out!

**Comment by sergiomb2** [comment]
> maybe we need to setup sourceforge the first in list?

@paulcarroty , for me,  you may do whatever you think is best , be my guest :) 
@mrpg99 googledrive mirror was removed , please make sure you have unitedrpms.repo updated
