### ISSUE TITLE
New website -> Monetization + Donate -> Public Koji/Copr for URPMS

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#46]
* Why we need a new website?

GH Pages are great, but we can't use it from instructions. This is very strange. https://github.com/UnitedRPMs/unitedrpms.github.io/issues/2

* Monetization

The best way from my experience is Google Adsense. We need a minimum 10-20 articles - probably some simple how-tos for software from URPMS repository. Maybe someone from us have an account? We can also use something like a [Patreon](https://www.patreon.com/) for donation.

* Public Koji/Copr for URPMS

I prefer Copr, it's more easy for configuration. Maybe [Hetzner CX20](https://www.hetzner.de/de/hosting/produkte_vserver/cx20) will be good for the beginning.

* Resume

So, we really need it @kuboosoft @sergiomb2 ? Or everything is fine with "pirate builds" and Gitlab & SF? I think this is the next stage. It will be very interested to read about Postinstallerf experience.

**Comment by kuboosoft** [comment]
@paulcarroty is very problematic, remember, exist packages limited by licenses, receive money for it, is dangerous.. For my the site is fine, only needs change a theme different. Maybe we can make a blog magazine... or planet..

> 
GH Pages are great, but we can't use it from instructions. This is very strange. UnitedRPMs/unitedrpms.github.io#2

Answer: https://github.com/UnitedRPMs/unitedrpms (a rpm for our repository)

> The best way from my experience is Google Adsense


I have a popular blog in Spanish (I publish articles) and i receive money here ( money for a cup of coffee, and my time, while I work with my project). If you are a good blogger you will obtain much money, Patreon sounds fine.

**Comment by paulcarroty** [comment]
@kuboosoft 

> is very problematic, remember, exist packages limited by licenses, receive money for it, is dangerous..

If it was very dangerous that RPMFusion and others would have big problems many years ago. We talk about web content & ads, not about software selling.

> For me the site is fine, only needs change a theme different. Maybe we can make a blog magazine... or planet.. and earn income from there.

The theme is not a problem - many HTML5 themes is available for static engines like Jekyll etc. And our package list maybe don't enough for some users, more instructions, how-tos and screenshots will be better; + post `what we add and how it works`, `how to do this things with our packages` etc. I use the [OpenShift](https://www.openshift.com/) for my projects (need a credit card, no money).

> Answer: https://github.com/UnitedRPMs/unitedrpms (a rpm for our repository)

Github use HTTP-only CDNs and traffic potentially can be snooped and redirected to bad source, including your RPM, our GPG key etc. It's not good.

> I do not consider bad our work with Gitlab & SF

It works good, we need a copr/koji.

> If you are a good blogger you will obtain much money, Patreon sounds fine.
> See Hostagator, godaddy haha

No, thanks.

12 months * $10 = $120 per year - not big money for Google Ads (without alternatives, it's bad).

**Comment by kuboosoft** [comment]
> Github use HTTP-only CDNs and traffic potentially can be snooped and redirected to bad source, including your RPM, our GPG key etc. It's not good.


Then; Fedora project, rpmfusion, all! have the same problem... Do you remember the history about [Linux Mint](http://blog.linuxmint.com/?p=2994)? man, Its paranoid... All has a mirror list. We can include a MD5 signature to our rpm repository and the people can check the MD5 signature...

> It works good, we need a copr/koji.
Yes but, we need a dedicated server, with high broadband... = $120 per year hahaha

**Comment by paulcarroty** [comment]
> man, Its paranoid

It's potential security issue and should be fixed.

> Fedora project, rpmfusion, all! have the same problem...

Don't matter.

 > we need a dedicated server, with high broadband

Good SSD VPS and $120 doesn't looks laughably. But you can always compile chromium, vlc and kodi on your localhost :smiley:

**Comment by paulcarroty** [comment]
https://github.com/nayafia/lemonade-stand

**Comment by paulcarroty** [comment]
I need we should to buy a server/vps from OVH in future and support them :smile: 

https://www.reddit.com/r/linux/comments/4ov74y/ovh_founder_on_twitter_canonical_is_attempting_to/
