### ISSUE TITLE
[Ready] F25 thread 

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#47]
http://rpmfusion.org/ImportantDependencyLists

**Comment by kuboosoft** [comment]
I recommend change to F25 when rpmfusion is ready for Fedora 24. @paulcarroty @sergiomb2  https://github.com/UnitedRPMs/unitedrpms

**Comment by sergiomb2** [comment]
I have to work for rpmfusion , kwizart wrote to me today pkgdb is ready (in rpmfusion of course)

**Comment by paulcarroty** [comment]
I think we need a mass rebuild for F25 after release and new repo. F24 repo will be also active.

**Comment by kuboosoft** [comment]
@paulcarroty , yes, a mass rebuild, but not in this moment, maybe a month after the official release Fedora 24... I'm undecided if I upgrade ffmpeg or not, isn't has a significant change, but it fixes some  issues.

**Comment by paulcarroty** [comment]
> isn't has a significant change, but it fixes some issues. 

Do it, not a problem. With some command magic we need to resolve which packages will need a rebuild.

So, I'm just for fan was rebuild all of postinstallerf packages, you use some archived versions of GCC :smile: 

Well, we can merge all postinnstallerf packages, I can's see any problem with storage/traffic, but someone from us must to learn how to use Github for all packages :smile_cat:

**Comment by sergiomb2** [comment]
@paulcarroty http://rpmfusion.org/ImportantDependencyLists we just need mass rebuilds when soname bumps , i.e. when x264-libs change from /usr/lib64/libx264.so.148 to /usr/lib64/libx264.so.150 , because we will also get broken deps , and when compilers change i.e. when gcc goes from 4 to 5

**Comment by paulcarroty** [comment]
> http://rpmfusion.org/ImportantDependencyLists

great

Before any change of x26?, ffmpeg, gcc or others we must have the ready shortlist.

**Comment by sergiomb2** [comment]
> Before any change of x26?, ffmpeg, gcc or others we must have the ready shortlist.

no :) ( except x265)

**Comment by paulcarroty** [comment]
> no :) ( except x265)

why? x264 use gstreamer, ffmpeg, mpv/vlc etc

**Comment by sergiomb2** [comment]
btw today x264 update his git http://git.videolan.org/gitweb.cgi/x264.git/?p=x264.git;a=summary 
but no soname bump , x264-0.148-20160614-a5e06b9.tar.bz2 so we just need build x264 , when x264-0.150 we will need rebuild all x264-libs dependencies .

**Comment by kuboosoft** [comment]
> Well, we can merge all postinnstallerf packages, I can's see any problem with storage/traffic, but someone from us must to learn how to use Github for all packages 

haha only for my gngeo, I love "Street Figther" and others games hahaha
haaa but remember, maintain the packages, i can't  maintain it, Example openh264, was deleted here, and openh264 is the future; example, if someone installs openh264, Firefox enables support with "Hello" in Firefox... other, the openh264 of fedora  deleted the tools for openh264;  for me is a risk if I maintain a package of potinstallerf here if it  will deleted. ;)

**Comment by paulcarroty** [comment]
> Remember exclude statistics track in the repository,

Statistics isn't the first important thing for us. And ~10 Gb hosting also.

> now we can make and install snaps packages in Fedora

> Important: on Fedora 24 you currently have to switch SELinux to permissive mode. 

No, thanks, I'm not interested.

**Comment by kuboosoft** [comment]
@paulcarroty I saw a guide from centos and explains how to make a automatic rule for selinux, and avoid have to switch SELinux to permissive mode ;P

With the updated gstreamer1 we can make the massive rebuild..
first rebuild all dependencies of ffmpeg; next ffmpeg; next gstreamer; next all dependencies of vlc,  then all packages will be updated without problem...

**Comment by paulcarroty** [comment]
SELinux need a high qualification. For typical user it's an evil animal. 

I think we should add the special note on website for software that need a permissive/disabled SELinux.

> With the updated gstreamer1 we can make the massive rebuild..
first rebuild all dependencies of ffmpeg; next ffmpeg; next gstreamer; next all dependencies of vlc, then all packages will be updated without problem...

OK, gstreamer will be updated today. I'm save in rpm repo the old versions to prevent dependency hell.

**Comment by paulcarroty** [comment]
I'm wait for new ffmpeg srpm, then will build it and rebuild:

* cmus
* gpac 
* libquicktime
* mpv/mplayer/smplayer
* kdenlive/openshot
* chromium
* audacity
* foobnix
* kodi
* vlc

Well, we need automation for future ffmpeg updates.

**Comment by kuboosoft** [comment]
> SELinux need a high qualification. For typical user it's an evil animal. 
no, is easy, the user only needs import the rule :), also is possible include in the rpm...

**tip for a mass rebuild**

The base, first rebuild all dependencies of ffmpeg, next all is easy.  Isn't necessary update ffmpeg; only when it provides important changes :)

**Comment by paulcarroty** [comment]
@kuboosoft, OK, we'll do it together with @sergiomb if you're not interested.

**Comment by paulcarroty** [comment]
@kuboosoft the answers for your hangout's message:

1. We use the `add_packages.sh` script for adding/update/sign/sync with SF/etc , check the `/repository` directory.

2. As I write above, it's too early to F25 mass rebuild. If you want to do it now - remember what we **must be ready** to mass rebuild at 1-2 weeks after F25 branching - a lot of major updates. And we need also automate it.

3. Your suggesting about new structure is bad - doesn't use the `repository`, it's reverved for F24.

4. No keys and another private information in hangout's and another unsecure service. Decrypt it with your private GPG key.

**Comment by kuboosoft** [comment]
>  paulcarroty ... As I write above, it's too early to F25 mass rebuild. If you want to do it now - remember what we must be ready to mass rebuild at 1-2 weeks after F25 branching - a lot of major updates. And we need also automate it.

1) We need  test our packages with ffmpeg 3.1
2) You can't automate all.  You need apply patches and test all; and make the minimum  'massive rebuild base'.  What includes a 'minimum massive rebuild base'?
a) ffmpeg
b) gstreamer*
and others

When you have this packages reduces the time for other programs, who requires the dependencies...

> Your suggesting about new structure is bad - doesn't use the repository, it's reverved for F24.

Is more coherent  provide a directory with releases (24..25..26), check up.

https://sourceforge.net/projects/unitedrpms/files/repository/25/

Examples:
http://fedora.mirror.digitalpacific.com.au/linux/releases/25/
Various official mirrors of Fedora
https://admin.fedoraproject.org/mirrormanager/mirrors/Fedora/development/x86_64

It's just a suggestion...
I think so  your problem is you no want move the f24 release. Well you will remember me in the future "I told you". Don't worry now :)

Well; I stopped my 'base mass rebuild" I want see how to you make a massive rebuild with all ;)

Other
I am afraid. You are adding more packages. Its a problem. You in the future will maintain all? when a man make a project, is necessary write a line; the viable and the non-viable, the infrastructure human, and material. Tells you so someone with experience; I maintain three 'releases' in 32 and 64-bit architecture, with 215 packages ... again you will remember me in the future "I told you"

Good wishes

**Comment by paulcarroty** [comment]
> If you want a project parallel to rpmfusion (working the same release), sorry but then the project changed. 

How?

> 1) We need test our packages with ffmpeg 3.1

Yep

> 2) You can't automate all. You need apply patches and test all; and make the minimum 'massive rebuild base'. What includes a 'minimum massive rebuild base'?

We (you're in or out now?) can automate most popular tasks: mass rebuild after upgrade: x264-265, ffmpeg, gstreamer - resolve their depends and automatically rebuild. + mass rebuild for new Fedora release.

> Is more coherent provide a directory with releases (24..25..26), check up.

Not inside `repository`, because handle 2+ repository into one git three it's stupid overhead.

* repository
* 25
* 26

or

* 24 (renamed repository) 
* 25
* 26

> I want see how to you make a massive rebuild with all ;)

`man copr-cli`, it's easy and not a secret. But URPMS need koji in future, it's non-alternative.

> I am afraid. You are adding more packages. It's a problem. You in the future will maintain all?

Yep. It's not a problem if people add a package and support them in future.

**RESUME**

So, you want to do a F25 rebuild right now and want to see how I do it? Right? What you do in  `my 'base mass rebuild"`? Which is your plan?

**Comment by sergiomb2** [comment]
why not duplicate repository and 24 ? , After we update unitedrpms-release and don't break user experience , after a few months we may remove repository dir or even not but just update package in 24

**Comment by paulcarroty** [comment]
> why not duplicate repository and 24 ?

Good idea but do it will be not easy @sergiomb2 . SF supports symlinks? In Gitlab we'll probably need to change origin everytime.

**Comment by kuboosoft** [comment]
![Unitedrpms in this moment](https://s32.postimg.org/jk934y9l1/unitedrpmsee.jpg)

**Comment by paulcarroty** [comment]
@kuboosoft wow, great scheme. About "no support for rawhide" - I use URPMS with rawhide for beginning.

I'm busy now, but have plan for F25 mass rebuilding in near future. You and @sergiomb2 also can help with mass_rebuild script for automation with x264/x265/ffmpeg/new release etc.

**Comment by kuboosoft** [comment]
In rawhide I use my local F.25 (unitedrpms-base, made in F25... patched, update..); but the people are mixing unitedrpms and rpmfusion in Fedora 24 (Personaly I only use the unitedrpms in Fedora 24), and exist broken dependencies for people mixing rpmfusion+unitedrpms... 

I have solved it; I have a lot of work, and I'm very tired; but tomorrow or the next week I will upload two tar files (F24+F25) then you can sync the repositories... With the base for F25; a simple script can make a massive rebuild all src.rpm in a step :)

![](https://s31.postimg.org/q6alikp63/f25_build.png)

**Comment by paulcarroty** [comment]
@kuboosoft wow, you're a hero! Great!

>  I will upload two tar files (F24+F25)
F24? src.rpm?

So, list of modified specs will be very helpful for github. We can use: branches, universal specs or directories with packages which need massive rework. @sergiomb2

**Comment by kuboosoft** [comment]
also I will update the git repository, don't worry ;)

**Comment by paulcarroty** [comment]
I think that specs like `ffmpeg-3.02`, `ffmpeg-3.1`, `gstreamer-1.8`, `gstreamer-1.9` it's more comfortable than a branch for every release.

**Comment by kuboosoft** [comment]
The capture is old; I am using the current gstreamer1.9... ;)

**Comment by paulcarroty** [comment]
gstreamer1.9 only in Rawhide now. We of course can ported it to F24 :smile: , but break a lot of software.

**Comment by kuboosoft** [comment]
Also, I ported gstreamer 1.9 for F24; I updated other packages;  yes I made a massive rebuild but works fine ;)
I needed make it, because the next months, I won't have time for it.

![](https://s32.postimg.org/bahj413zp/enjoy24.png)

**Comment by paulcarroty** [comment]
@kuboosoft pls upload it and I'll open F25 repo.

**Comment by kuboosoft** [comment]
I don't have time for open the F25 and sync, but in this moment, I am uploading the packages base (by parts). Fedora 24 is complete. You need download and merge with the next instructions...

(part 1)
united24aa
http://www26.zippyshare.com/v/KR2Yfpyg/file.html

Part2)
united24ab
http://www100.zippyshare.com/v/Lk1XfneH/file.html

Part3)
united24ac
http://www26.zippyshare.com/v/N1cOvG5g/file.html

(part4)
united24ad
http://www28.zippyshare.com/v/aMxAIXjU/file.html

**How to merge?**

`cat united24* > enjoy24.tar.xz`

**Comment by paulcarroty** [comment]
@kuboosoft great! I'm download and unpack it, but must recompile & test the chromium package before merging. Do you use the same *src.rpm for F25? If yes - I can recompile it for F25.

**Comment by kuboosoft** [comment]
yes; the same, I see a new version for ffmpeg, but has minors changes. I think so no affect the dependencies, we need test it.

**Comment by paulcarroty** [comment]
@kuboosoft don't waste your time for the F25 uploading - I need only a kodi if you  have it.

**Comment by kuboosoft** [comment]
Yes, I can upload the rpm in github repository...

**Comment by paulcarroty** [comment]
@kuboosoft great, in GH releases please :-)

**Comment by kuboosoft** [comment]
Ok :+1:

**Comment by paulcarroty** [comment]
What I have now, @kuboosoft :

F24 (without your packages) - http://paste.fedoraproject.org/391567/46860901/

F25 - http://paste.fedoraproject.org/391569/46860908/

**Comment by paulcarroty** [comment]
And I'm searching the software for delete rpm package duplicates because handle it yourself will be TOO slow.

**Comment by kuboosoft** [comment]
@paulcarroty wait; I only need upload 2 parts and  it will complete F25  (300mb). You only need update minors packages... The hard part is already made

**Comment by paulcarroty** [comment]
@kuboosoft OK, I'm now work with F24.

So, which versions we still alive in repo? I vote for 2, because a working reserve is necessary. I'm add to `add_packages.sh`:

```
rm $(dnf repomanage --keep=1 --old /path/to/repo/)
```

**Comment by kuboosoft** [comment]
F25
http://pastebin.com/raw/aTjZKHTR

F24
http://pastebin.com/raw/EEAFWcbx

**Comment by paulcarroty** [comment]
I have all exclude kodi addons for F25. But maybe it's better to recompile it with ffmpeg 3.1.1

**Comment by kuboosoft** [comment]
The kodi-pvr- addons no needs ffmpeg... But I will test with the new version of ffmpeg 3.1.1 if affected other dependencies... with a chroot (mock)

F25

united25aa  (part 1)
http://www20.zippyshare.com/v/Q6p3feHf/file.html

united25ab (part2)
http://www8.zippyshare.com/v/6N3eGw63/file.html

united25ac (part3)
http://www12.zippyshare.com/v/KoqbNxdy/file.html

united25ad  (part4)
http://www12.zippyshare.com/v/9rGa9xjC/file.html

united25ae (part5)
http://www77.zippyshare.com/v/QKVseF51/file.html

united25af (part6)
http://www89.zippyshare.com/v/rkI87vJo/file.html

**How to merge?**

`cat united25* > enjoy25.tar.xz`

**Comment by paulcarroty** [comment]
@kuboosoft all bugs with broken depends and "unitedrpms updates gstreamer to unstable branch" is now yours, and it's totally rightly.

**Comment by paulcarroty** [comment]
Test F25 repo:

https://gitlab.com/UnitedRPMs/25/raw/master/x86_64/
https://gitlab.com/UnitedRPMs/25/raw/master/x86_64/debug/
https://gitlab.com/UnitedRPMs/25/raw/master/srpm/

**Comment by kuboosoft** [comment]
> @kuboosoft all bugs with broken depends and "unitedrpms updates gstreamer to unstable branch" is now yours, and it's totally rightly

?? remember rebuild the others packages made by you... all packages (base) was tested since june 2016. In theory this project provides packages for releases in development or not!. Fedora 24 is your first objetive?. Or you want replace rpmfusion? tell me what you think. In theory we are using F25 (rawhide)...

**Comment by paulcarroty** [comment]
@kuboosoft, sorry, I forget about smile in the end :D :D

About gstreamer - I revert tó 1.8 because it's totally break  gnome de in F24.

> I don't have problem making my ow patches etc... but you?

Remember who fix the obs-studio screen record :D

**Comment by kuboosoft** [comment]
In my machine with F24...
![](https://s32.postimg.org/czr7zq8xh/image.png)
without problem :) can you share the log about the problem with gnome..

obs-studio. As  I said  I haven't a video card with support DRI3 and opengl3, then in this cases i can't test this packages, similar to nvidia video cards...  and the next week I will buy a Ati haha

**Comment by paulcarroty** [comment]
https://github.com/UnitedRPMs/unitedrpms.github.io/issues/6#issuecomment-233135965

**Comment by paulcarroty** [comment]
+ all thread
