### ISSUE TITLE
RPMFusion is back in business 

### ISSUE THREAD

**Issue by sergiomb2** [UnitedRPMs/packages#52]
Hi, 
http://download1.rpmfusion.org/free/fedora/updates/testing/24/SRPMS/repoview/index.html
you may follow new builds here : http://koji.rpmfusion.org/koji/builds
I ask , that you help in update RPMFusion for F24 , with experience of unitedrpms , what you suggest
to update ? can you give me a diff **but** it need to be make by the book , I can't accept hacks , sorry is the rules of RPMFusion.  
I'm provenpackager and also a sponsor , I can sponsor you , if you promise that you do the things by the book , thanks .
I'm maintainer of smplayer and I will update it soon ... 

Big thanks.

**Comment by kuboosoft** [comment]
Thanks @sergiomb2 ;  Openshot 2.0.7; is very inestable. Minors updates for ffmpeg will avoid problems with kodi and others  players.

**Comment by sergiomb2** [comment]
> Thanks @sergiomb2 ; Openshot 2.0.7; is very inestable. Minors updates for ffmpeg will avoid problems with kodi and others players. 

 Thanks , where are the minors updates ?  or you mean update from ffmpeg 3.0.1 to 3.0.2  ? and yeah we have here all fixes for  Openshot 

@paulcarroty don't you want join to the big team which is RPMFusion ? , anyway I'm thankful to you and your work here , unitedrpms still have many packages like atom and others tools that aren't in other repository ...

**Comment by paulcarroty** [comment]
@sergiomb2 no reason to go from the better project.

@kuboosoft just say finally: we need ffmpeg 3.0.2 or not? It should solve our problems? Because mass rebuilding isn't a problem (for me, lol).

**Comment by sergiomb2** [comment]
> @sergiomb2 no reason to go from the better project.

I'm not asking to go , just to join or help on other project , I work for both projects for example 

> @kuboosoft just say finally: we need ffmpeg 3.0.2 or not? It should solve our problems? Because mass rebuilding isn't a problem (for me, lol).

no need mass rebuild , because we don't have soname bump and we use ld libraries , not static libs , anyway yes we should update  ffmpeg

**Comment by paulcarroty** [comment]
> no need mass rebuild , because we don't have soname bump and we use ld libraries , not static libs

Chromium builded with ffmpeg 3.0.1 doesn't work with 3.0.2 IRL. The same with most applications.

**Comment by paulcarroty** [comment]
> anyway yes we should update ffmpeg

OK. @kuboosoft did you have a time for update?

**Comment by kuboosoft** [comment]
@sergiomb2 I don't love the updates for ffmpeg, if it affect other packages; first we need test it, before update.   

> and yeah we have here all fixes for Openshot

mmm, yes and beta; fix not for Intel i915 and similar crap video cards.. I am using a old version and works fine haha

@paulcarroty Arch Linux uses the internal ffmpeg (also ubuntu), it can avoid conflicts with ffmpeg... My attempt for compile chromium is a crap, it take about +24hrs (canceled before 20 hrs). I made a chromium-unstable rpm with the packages from ubuntu, and patch and delete some things, and avoid + 24hrs lost.

**Comment by sergiomb2** [comment]
chromium is open source can be built in copr but I wonder how goes ffmpeg 

    dnf copr search chromium 

https://copr.fedorainfracloud.org/coprs/lantw44/chromium/
http://www.tfcis.org/~lantw44/cgit/copr-rpm-spec/tree/chromium/chromium/chromium.spec
```
# This spec file is based on other spec files and PKGBUILDs available from
#  [1] https://repos.fedorapeople.org/repos/spot/chromium/
#  [2] https://copr.fedoraproject.org/coprs/churchyard/chromium-russianfedora-tested/
#  [3] https://www.archlinux.org/packages/extra/x86_64/chromium/
```

**Comment by paulcarroty** [comment]
@sergiomb2 All Copr chromium repos doesn't support ffmpeg and HTML5 Multimedia. Our spec is builded from RFR and use the external ffmpeg and URPMS bookmarks/about & supports multimedia.

> Arch Linux uses the internal ffmpeg

@kuboosoft no shitty bundles, please. 

I can recompile chromium with new ffmpeg, it's not a problem (cost 5-7 hours), don't ask where.

**Comment by paulcarroty** [comment]
> My attempt for compile chromium is a crap, it take about +24hrs (canceled before 20 hrs)

Oh lol, you're an extreme. We definitely need a builder. In future if I will have some free time, I (we) need to create a website+blog with some how-tos/news; include it to adsense and [support](https://www.ovh.com/ca/en/vps/) OVH against Canonical  :smiley:

**Comment by sergiomb2** [comment]
> Chromium builded with ffmpeg 3.0.1 doesn't work with 3.0.2 IRL. The same with most applications. 

if that happens with Chromium I believe , but others applications I don't believe , it means that ffmpeg have abi breaks , have you some other example that I can check ?

**Comment by paulcarroty** [comment]
https://github.com/UnitedRPMs/packages/issues/47#issuecomment-228349018

**Comment by kuboosoft** [comment]
> @kuboosoft no shitty bundles, please. 

> I can recompile chromium with new ffmpeg, it's not a problem (cost 5-7 hours), don't ask where.

sure,  and you applied a patch from Arch Linux in your .spec file, hahaha.

Rebuild the src.rpm in copr does not take 5-7 hours, then? I will see your changelog directly in the rpm hahaha :P.  The packed chromium in Arch, has many similarities excluded by ffmpeg... I made a  .spec with ffmpeg included "-Duse_system_ffmpeg=0" but only think wait +24 hrs is the death...

**Comment by paulcarroty** [comment]
--> #54

**Comment by sergiomb2** [comment]
@paulcarroty  , I see you like close issues lol , but why this one ? lol ... once RPMFusion is healthy   , we can talk about remove duplicated  packages  ... and focus in postintaller and many other packages, chorium etc 
Now I have the soccer game to see Portugal - Croatia ...

**Comment by paulcarroty** [comment]
> but why this one ?

Because lost post about ffmpeg and not about RPMF. You can reopen it if you need.

> Now I have the soccer game to see Portugal - Croatia ...

I have seen the IPTV livestream, great game from Portugal.

**Comment by paulcarroty** [comment]
> we can talk about remove duplicated packages ... and focus in postintaller and many other packages, chorium etc 

OK, https://github.com/UnitedRPMs/packages/issues/13

**Comment by sergiomb2** [comment]
> OK, #13 

OK that is a good reason 

> I have seen the IPTV livestream, great game from Portugal.

Some other packages that I like add to this project , is livestream plugins and acestream for kodi :smile: but should take a while .

**Comment by paulcarroty** [comment]
> is livestream plugins 

AFAIR some software called a `livestreamer` is available, but today mpv have the same functional (with youtube-dl).

> and acestream

And sopcast :smile: If it not dead.
