### ISSUE TITLE
Atom with broken dependencies

### ISSUE THREAD

**Issue by lucaciavatta** [UnitedRPMs/packages#53]
Hi again!
I updated my F24 Beta to F24 Final and, after a dnf update, I got this issue:

`Skipping packages with broken dependencies:
 atom                         x86_64 1.8.0-2.gitf89b273.fc24   unitedrpms  20 M
` 

Any idea to solve it?

**Comment by aljazzair** [comment]
https://github.com/UnitedRPMs/packages/issues/51

**Comment by lucaciavatta** [comment]
Sorry, I didn't investigate through closed issues.

`sudo dnf install atom --best --allowerasing -y`

solved the issue.
Thanks for your time.
