### ISSUE TITLE
Mass rebuild for ffmpeg 3.0.2 progress

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#54]
- [x] create ffmpeg 3.02 package
- [x]  resolve dependencys list
` # dnf download --source libquicktime mlt minidlna cmus mpv gnome-mpv mplayer smplayer kdenlive openshot chromium audacity-freeworld foobnix kodi vlc obs-studio`

- [x] bump versions and rebuilding
```
// install sources
$ rpm -i *src.rpm
$ cd ~/rpmbuild/SPECS/

// bump
$ rpmdev-bumpspec -r -c "Rebuild with new ffmpeg" *.spec

// create the src.rpms
rpmbuild -bs *spec
```

- [x] testing
- [x] upload to repository

[Test repo](https://copr.fedorainfracloud.org/coprs/paulcarroty/test-3.0.2/builds/)

**Comment by kuboosoft** [comment]
First is necessary test.  You need make a local repository and test, using a chroot ( with mock), no upload the rpm;  because you will breaking all.... How to test all?

```
mock -r fedora-rawhide-x86_64 --init
cd foo/path/rpms
mock -r fedora-rawhide-x86_64 --install *.rpm
```

**Comment by paulcarroty** [comment]
> You need make a local repository

**Public** repository 'cause I need help in testing. Mock is good, but I prefer the more clean and fast LiveCD.

**Comment by paulcarroty** [comment]
80% of packages doesn't have any problems. I've planned to push it tommorrow - it's for "you need to speak with the team" @kuboosoft
