### ISSUE TITLE
The one way to add URPMS repository

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#55]
Now we have the 3(!) [ways](https://github.com/UnitedRPMs/unitedrpms.github.io), it's looks abnormally. My idea - use the original Fedora way and provide the  200% working `unitedrpms-release` (or unitedrpms if @kuboosoft want it, look https://github.com/UnitedRPMs/unitedrpms-release/issues/3).

**Comment by paulcarroty** [comment]
OK, let it be without `-release`. But it will be the one way to add URPMS, I delete the others.

> When our repository makes a massive rebuild to 25

2016-07-26

> https://sourceforge.net/projects/unitedrpms/files/repository/24/x86_64

No. We have a one git three in /repository/ and it's only for F24. We'll use /repository25/ or any outside directory.

**Comment by kuboosoft** [comment]
@paulcarroty chek it up; https://sourceforge.net/projects/unitedrpms/files/repository/
We need move the currents rpms to 24/foo_arch/
I am making the base part for the massive rebuild; can see your handouts? I wrote you here.

**Comment by paulcarroty** [comment]
No, doesn't touch the `repository`! All changes only outside! Because we need the only one git tepo for each release. And our old repo config must work. 

About mass rebuild etc - tomorrow.

**Comment by paulcarroty** [comment]
@kuboosoft 

> can see your handouts? I wrote you here.

What? I can't understand.

About mass rebuild - I think we can do it at 1 week before/after the F25 branching.
