### ISSUE TITLE
ffmpeg with fdk aac and other

### ISSUE THREAD

**Issue by NNois** [UnitedRPMs/packages#56]
Hi,
How can we get ffmpeg with the most popular codec installed ?

**Comment by paulcarroty** [comment]
Hello @NNois, please define which `the most popular codec` you need? Our ffmpeg configuration is [here](https://github.com/UnitedRPMs/ffmpeg/blob/master/ffmpeg-3.02.spec).

**Comment by NNois** [comment]
Hi Paul,
My bad, and my bad english, I mean mostly fdkaac.
Thanks !
