### ISSUE TITLE
Gitlab alternative 

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#59]
Today our repo is big because we have a lot of new packages, store two latest versions and going to F25 repo. Compression and 2*size reserve make git slow.

Summary: we need a fast and >= 10Gb mirror. Any ideas?

**Comment by kuboosoft** [comment]
mmm a free alternative impossible... but '[launchpad](https://launchpad.net/)' can help us ;)
As I said in others conversations we are adding more packages outside our capacity... prudence. 

A git repository for rpms is only time for gitlab close it. Also we need disable the track for repository  (repodata) in Source Forge in each update.

**Comment by paulcarroty** [comment]
> As I said in others conversations we are adding more packages outside our capacity... prudence.

You have much more "packages outside" in pf.

I have AWS free tier for 2017 and not decided now how to use it. 30 Gb SSD, 1 GB RAM, but limited iops and traffic.

**Comment by kuboosoft** [comment]
haha, but not complex packages as ffmpeg, vlc, kodi, chromium and others... :p
why no test with launchpad; I will testing with pf if it works or not... example you can import gitlab here automatic... remember various distributions based in Ubuntu, uses lauchpad as repository, as Linux Mint, Elementary and others...

**Comment by paulcarroty** [comment]
> why no test with launchpad?

launchpad can build/test rpm packages? really?

> haha, but not complex packages as ffmpeg, vlc, kodi, chromium

no complex/popular/useful software - no profit. doing something for 10-20-30 downloads - waste of time.

> remember various distributions based in Ubuntu, uses lauchpad as repository, as Linux Mint, Elementary and others

I'm not interested in deb-based Linux distributions.

**Comment by kuboosoft** [comment]
?? build rpm here no;  but maybe we can upload sources and rpm... 

> I'm not interested in deb-based Linux distributions.
??? is a axample "genius" haha,  the context is; this offers the GB needed ;)

**Comment by paulcarroty** [comment]
> ?? build rpm here no; but maybe we can upload sources and rpm...

Let's be more clear: you suggest to use the launchpad as rpm/srpm hosting?

**Comment by kuboosoft** [comment]
@paulcarroty ; yes :)

**Comment by paulcarroty** [comment]
@kuboosoft it's will be a great trolling :smile_cat:
