### ISSUE TITLE
Openshot crash with segfault

### ISSUE THREAD

**Issue by x11tete11x** [UnitedRPMs/packages#60]
Hi guys, more testing :D

Opeshot crash when you move the slider on the track added (even with no track added when you move the slider, crash)

Log: [openshot.txt](https://github.com/UnitedRPMs/packages/files/368284/openshot.txt)

more info: It's weeeeeird but the issue it's exactly the same as this veeery [old bug](https://lists.launchpad.net/openshot.developers/msg02755.html) 
thx!

**Comment by kuboosoft** [comment]
mmm; I will check the problem. thanks for report it.

**Comment by x11tete11x** [comment]
Thank you for all efforts! Tus repo is getting better and better :D

**Comment by paulcarroty** [comment]
@x11tete11x @kuboosoft thank for your contribution.

openshot-legacy and shotcut was added except shotcut have a compilation problem with F25.

**Comment by kuboosoft** [comment]
@paulcarroty can you share the log? I compiled without problem...

**Comment by paulcarroty** [comment]
@kuboosoft http://paste.fedoraproject.org/393382/9363714/
