### ISSUE TITLE
Kodi cant reproduce anything

### ISSUE THREAD

**Issue by x11tete11x** [UnitedRPMs/packages#62]
Hi guys!, me, with more logs xD

Kodi cant reproduce anything (even it's in the local machine)

Fedora 24 + Unitedrpms + Nvidia Drivers

Log: 
[kodilog.txt](https://github.com/UnitedRPMs/packages/files/374665/kodilog.txt)

Thx!

**Comment by kuboosoft** [comment]
thanks, for report. The current ffmpeg isn't compatible with Kodi Jarvis... We will solve it.

**Comment by paulcarroty** [comment]
Fixed with new build.
