### ISSUE TITLE
Warning: binaries is now deprecated in Git repository

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#63]
Every Github repo is limited for 100 MB, and big binary rpm/srpm can easy overflow it.

From now we use the Github releases - 2 GB/file limit, not limits for number of files.

How to use Github releases (with screenshots): https://help.github.com/articles/creating-releases/ 

You can also get srpm from our repository:

```
# dnf download --source packagename
```

@kuboosoft

**Comment by kuboosoft** [comment]
bad news :/ is a serious problem. but solved "dnf download --source packagename"
