### ISSUE TITLE
sourceforge.net repo not working for me

### ISSUE THREAD

**Issue by srakitnican** [UnitedRPMs/packages#65]
Just installed UnitedRPMs F25 repo, and I am unable to install or update any package due to following dnf error:
```
Error: Error downloading packages:
  Cannot download a52dec-0.7.4-20.fc25.x86_64.rpm: All mirrors were tried
```

I noticed that F25 UnitedRPMs repo provides only one mirror which never did work for me, it was always skipped.

**Comment by paulcarroty** [comment]
@srakitnican looks like your local network problem:

```
dnf download a52dec
Last metadata expiration check: 3:52:55 ago on Fri Aug 12 09:08:36 2016.
a52dec-0.7.4-20.fc25.x86_64.rpm                        30 kB/s |  64 kB     00:02  
```

Try direct link: `https://sourceforge.net/projects/unitedrpms/files/25/x86_64/a52dec-0.7.4-20.fc25.x86_64.rpm`

**Comment by srakitnican** [comment]
`dnf install https://sourceforge.net/projects/unitedrpms/files/25/x86_64/a52dec-0.7.4-20.fc25.x86_64.rpm`
works

**Comment by srakitnican** [comment]
> looks like your local network problem
I have squid cache server setup with intelligentmirror. I 've cleared https_proxy= variable and now is working.

**Comment by srakitnican** [comment]
But I have no idea why, it downloads repodata successfully, but fails to download package. If anyone is curious here are the logs:

Squid: http://pastebin.com/yDXh4NfZ
dnf upgrade: http://pastebin.com/AwPPV9Gm

**Comment by paulcarroty** [comment]
> Interrupted by header callback: Server reports Content-Length: 385 but expected size is: 156282 

385 bytes sound like error webpage. Maybe dnf handle incorrect your proxy. Debug dnf and see what happens inside.

**Comment by srakitnican** [comment]
After some research found out that librepo handles downloading for dnf. After enabling some debugging lines [1] I found out that url passed to it seems correct, but for some reason it is not working [2] when my "proxy=" dnf.conf line is enabled. AFAICT squid is just passing https urls through because it is unable to cache encrypted connection anyway. 

[1] http://unix.stackexchange.com/a/252774
[2] http://pastebin.com/xVgEkqdz

However, curl is working with proxy without any problems, squid even manages to cache the package between redirects it seems to go back to http.
```
$ curl -OL https://sourceforge.net/projects/unitedrpms/files/25/x86_64/a52dec-0.7.4-20.fc25.x86_64.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   383    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   455    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100   369  100   369    0     0    166      0  0:00:02  0:00:02 --:--:--   166
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100 65626  100 65626    0     0  28724      0  0:00:02  0:00:02 --:--:-- 28724
```

```
1471027158.120    332 192.168.1.28 TCP_MISS/302 935 GET http://downloads.sourceforge.net/project/unitedrpms/25/x86_64/a52dec-0.7.4-20.fc25.x86_64.rpm? - HIER_DIRECT/216.34.181.59 text/html
1471027158.130      6 192.168.1.28 TCP_REDIRECT/303 312 GET http://netix.dl.sourceforge.net/project/unitedrpms/25/x86_64/a52dec-0.7.4-20.fc25.x86_64.rpm - HIER_NONE/- -
1471027158.166     33 192.168.1.28 TCP_MISS/200 65993 GET http://127.0.0.1/intelligentmirror/rpm/a52dec-0.7.4-20.fc25.x86_64.rpm - HIER_DIRECT/127.0.0.1 application/x-rpm
```


I suspect redirects somehow interfere here but I have no idea how nor why.

**Comment by paulcarroty** [comment]
@srakitnican no idea, try to ask the dnf devs/community.
