### ISSUE TITLE
libglvnd messes up Intel driver

### ISSUE THREAD

**Issue by srakitnican** [UnitedRPMs/packages#66]
I have upgraded F25 and with it came a new package installed libglvnd. After a reboot gnome did not start again and by looking at Xorg.0.log this errors stand out:

```
[    45.265] (EE) AIGLX error: dlopen of /usr/lib64/dri/i965_dri.so failed (/usr/lib64/dri/i965_dri.so: undefined symbol: _glapi_get_dispatch_table_size)
[    45.265] (EE) AIGLX: reverting to software rendering
[    45.509] (EE) AIGLX error: dlopen of /usr/lib64/dri/swrast_dri.so failed (/usr/lib64/dri/swrast_dri.so: undefined symbol: _glapi_check_multithread)
[    45.509] (EE) GLX: could not load software renderer
```

By removing /etc/ld.so.conf.d/libglvnd-lib64.conf and rebuilding cache with ldconfig X starts again. If I try to remove libglvnd, it tries to remove gnome components with it:

```
# sudo dnf remove libglvnd
Dependencies resolved.
================================================================================
 Package                             Arch   Version         Repository     Size
================================================================================
Removing:
 gdm                                 x86_64 1:3.21.4-1.fc25 @fedora       2.1 M
 gnome-classic-session               noarch 3.21.4-1.fc25   @fedora       196 k
 gnome-initial-setup                 x86_64 3.20.1-1.fc25   @System       2.5 M
 gnome-session                       x86_64 3.21.4-1.fc25   @fedora       1.4 M
 gnome-session-wayland-session       x86_64 3.21.4-1.fc25   @fedora       7.4 k
 gnome-session-xsession              x86_64 3.21.4-1.fc25   @fedora        14 k
 gnome-shell                         x86_64 3.21.4-1.fc25   @fedora       9.5 M
 gnome-shell-extension-alternate-tab noarch 3.21.4-1.fc25   @fedora       9.9 k
 gnome-shell-extension-apps-menu     noarch 3.21.4-1.fc25   @fedora        26 k
 gnome-shell-extension-background-logo
                                     noarch 3.21.3-1.fc25   @System        56 k
 gnome-shell-extension-common        noarch 3.21.4-1.fc25   @fedora       555 k
 gnome-shell-extension-launch-new-instance
                                     noarch 3.21.4-1.fc25   @fedora       4.9 k
 gnome-shell-extension-places-menu   noarch 3.21.4-1.fc25   @fedora        23 k
 gnome-shell-extension-window-list   noarch 3.21.4-1.fc25   @fedora        55 k
 libglvnd                            x86_64 0.1.0-3.8277115.fc25
                                                            @@commandline 1.5 M
 pulseaudio-gdm-hooks                x86_64 9.0-1.fc25      @rawhide      354  

Transaction Summary
================================================================================
Remove  16 Packages

Installed size: 18 M
Is this ok [y/N]: n
Operation aborted.
```

See also: https://bugzilla.redhat.com/show_bug.cgi?id=1366310

**Comment by paulcarroty** [comment]
> I have upgraded F25 and with it came a new package installed libglvnd.
Did you use the nvidia drivers? `# rpm -e --nodeps libglvnd` can help.

**Comment by srakitnican** [comment]
Yes, thank you. I know about rpm --nodeps option. Just reporting the issue.

I am not using nvidia drivers as I don't have any nvidia related hardware on my machine.

**Comment by paulcarroty** [comment]
> I am not using nvidia drivers as I don't have any nvidia related hardware on my machine.

It's very strange. Can you find the transaction log?

```
# dnf history list | head
# dnf history info your_id
```

**Comment by srakitnican** [comment]
I've attached transaction log to redhat bug report: https://bugzilla.redhat.com/attachment.cgi?id=1190071

Is this what you are looking for?

**Comment by paulcarroty** [comment]
Yep, is it. It's probably a wine because other packages I have installed too, exclude Java and LO. Run:

```
# repoquery --whatrequires libglvnd --source | perl -pe 's/-\d.*?-\d+(\..*)?\.fc\d+(\..*)?.src.rpm//' | sort -u 
```

**Comment by srakitnican** [comment]
Hmm repoquery returns nothing. 
```
# dnf repoquery --whatrequires libglvnd --source 
Last metadata expiration check: 0:00:23 ago on Fri Aug 12 21:29:21 2016.
```

**Comment by paulcarroty** [comment]
I'm sure that it's wine - excluding method.

```
    Install  libglvnd-0.1.0-3.8277115.fc24.x86_64                                                   @unitedrpms
```
Why fc24? Which URPMS repo you use?

**Comment by paulcarroty** [comment]
P.S. Seems like you use the URPMS F24 repo for F25, Enable F25 repository and check the logs for libglvnd.

**Comment by srakitnican** [comment]
Umm yes, that was before, I didn't know that F25 repo was available. With F25 repo and packages is the same thing, and also X breaks.

```
# dnf remove libglvnd
Dependencies resolved.
============================================================================================================================================
 Package                                               Arch               Version                           Repository                 Size
============================================================================================================================================
Removing:
 gdm                                                   x86_64             1:3.21.4-1.fc25                   @fedora                   2.1 M
 gnome-classic-session                                 noarch             3.21.4-1.fc25                     @fedora                   196 k
 gnome-initial-setup                                   x86_64             3.20.1-1.fc25                     @System                   2.5 M
 gnome-session                                         x86_64             3.21.4-1.fc25                     @fedora                   1.4 M
 gnome-session-wayland-session                         x86_64             3.21.4-1.fc25                     @fedora                   7.4 k
 gnome-session-xsession                                x86_64             3.21.4-1.fc25                     @fedora                    14 k
 gnome-shell                                           x86_64             3.21.4-1.fc25                     @fedora                   9.5 M
 gnome-shell-extension-alternate-tab                   noarch             3.21.4-1.fc25                     @fedora                   9.9 k
 gnome-shell-extension-apps-menu                       noarch             3.21.4-1.fc25                     @fedora                    26 k
 gnome-shell-extension-background-logo                 noarch             3.21.3-1.fc25                     @System                    56 k
 gnome-shell-extension-common                          noarch             3.21.4-1.fc25                     @fedora                   555 k
 gnome-shell-extension-launch-new-instance             noarch             3.21.4-1.fc25                     @fedora                   4.9 k
 gnome-shell-extension-places-menu                     noarch             3.21.4-1.fc25                     @fedora                    23 k
 gnome-shell-extension-window-list                     noarch             3.21.4-1.fc25                     @fedora                    55 k
 libglvnd                                              x86_64             0.1.0-3.8277115.fc25              @@commandline             1.5 M
 pulseaudio-gdm-hooks                                  x86_64             9.0-1.fc25                        @rawhide                  354  

Transaction Summary
============================================================================================================================================
Remove  16 Packages

Installed size: 18 M
Is this ok [y/N]: n
Operation aborted.
```

**Comment by srakitnican** [comment]
```
# rpm -q --requires gnome-session | grep libGL
libGL.so.1()(64bit)
```
Is it possible that somehow matches libGL.so.1 from libglvnd package also?

**Comment by kuboosoft** [comment]
@paulcarroty who requires/provides libglvnd? 
https://github.com/UnitedRPMs?utf8=%E2%9C%93&query=libglvnd

**Comment by paulcarroty** [comment]
@srakitnican @kuboosoft what is libglvnd? It's OpenGL libraries from NVidia that replace the opensource original libraries. YEP, of course, libglvnd also include the `libGL.so.1` and dnf prefer it instead of original version.

Now I don't have a idea how to fix it and don't wand to know how many DE we're killed :-) But the problem is detected, and it's good.

**Comment by srakitnican** [comment]
Again, new update: http://pastebin.com/QD4CehXs, and with only unitedrpms and update-testing repo enabled http://pastebin.com/nEft3Wfz

I've created debugdata with dnf --debugsolver option in case it helps: https://db.tt/tDlCsf4o

**Comment by srakitnican** [comment]
It seems it is pulled by gstreamer1-plugins-bad-free this time.

$ sudo dnf upgrade gstreamer1-plugins-bad-free
Last metadata expiration check: 3:06:52 ago on Sat Aug 20 22:14:55 2016.
Dependencies resolved.
======================================================================================================
 Package                          Arch        Version                      Repository            Size
======================================================================================================
Installing:
 libglvnd                         x86_64      0.1.0-3.8277115.fc25         unitedrpms           206 k
Upgrading:
 gstreamer1-plugins-bad-free      x86_64      1.9.1-2.fc25                 updates-testing      1.8 M

Transaction Summary
======================================================================================================
Install  1 Package
Upgrade  1 Package

Total download size: 2.0 M
Is this ok [y/N]: n
Operation aborted.

**Comment by srakitnican** [comment]
Ok, I've added an exclude=libglvnd* to dnf and then found out that I was missing mesa-libGLES for some odd reason. After I've installed it it no longer wants to install libglvnd.

```
$ sudo dnf upgrade gstreamer1-plugins-bad-free
Last metadata expiration check: 3:43:14 ago on Sat Aug 20 22:14:55 2016.
Dependencies resolved.
======================================================================================================
 Package                            Arch          Version                Repository              Size
======================================================================================================
Upgrading:
 gstreamer1-plugins-bad-free        x86_64        1.9.1-2.fc25           updates-testing        1.8 M

Transaction Summary
======================================================================================================
Upgrade  1 Package

Total download size: 1.8 M
Is this ok [y/N]: 
```

**Comment by paulcarroty** [comment]
> then found out that it wants to install mesa-libGLES. After I've installed it it no longer wants to install libglvnd. For some odd reason it wasn't installed with "Fedora Workstation" dnf group at first.

@srakitnican maybe you was insalled F25 without "Fedora Workstation" group?

I've tried to reproduce the `gstreamer1-plugins-bad-free ` install/upgrade and it's works without `libglvnd`.

**Comment by srakitnican** [comment]
Nope, this was the command used: "--disablerepo=* --enablerepo=rawhide --nogpgcheck --installroot=/mnt groupinstall Fedora Workstation"

Transaction history: http://pastebin.com/U0vhtfFs

**Comment by paulcarroty** [comment]
Nvidia drivers was updated, and I tested it on fresh F26 - no problem.

**Comment by srakitnican** [comment]
This issue goes a little bit deeper then this package it seems but I agree, nothing to be fixed here it seems. Anyway working fine for me also since I've installed missing mesa-libGLES package.
