### ISSUE TITLE
Freetype: hinting is enabled by default

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#69]
freetype 2.7 is available in F26

https://www.mail-archive.com/freetype-announce@nongnu.org/msg00104.html

We need to delete our freeworld packages?

Seems like it's new hinting not disabled in official spec - http://koji.fedoraproject.org/koji/buildinfo?buildID=800291

**Comment by kuboosoft** [comment]
really? haha, Isn't necessary delete. Maybe the packager forgot it...
