### ISSUE TITLE
Document Package update policy

### ISSUE THREAD

**Issue by donateur** [UnitedRPMs/packages#70]
Hello,

I've looked through your documentation, but I could not find why a release of software was chosen.
Could you please document if your packages are all aimed to be "stable" and put some words around how versions of software are chosen for this repository?

**For example:**
I'm building a Fedora-based Home Theater PC and was very happy to find that you'd packaged a recent version of Kodi as well as providing kodi-pvr-addons!  Yay!

However you have provided Kodi 17.0 beta 1, which isn't stable yet.  Why is that?

I hope that this beta is just included in preparation for the release of Kodi 17 and that in future you will follow the _stable_ releases of Kodi.

Fedora aims to only provide major version updates  with new versions of the operating system.  For reference, the (wordy) equivalent Fedora policy is here: https://fedoraproject.org/wiki/Updates_Policy#Stable_Releases

I hope that your policy is aimed at keeping up to date with the current version of mature software like Kodi, rather than getting stuck behind.

Thank you!

**Comment by paulcarroty** [comment]
> but I could not find why a release of software was chosen.

Maintainer decide it. We always prefer working software. If latest version have interested features and can fix bugs, we'll use it. @kuboosoft maybe can tell more about it, also AFAIR `kodi 16` still available in URPMS repository.

**Comment by kuboosoft** [comment]
@donateur short answer; we maintain packages not only for F24. A package is updated to beta for 4 reasons.

1) Drastic changes (needs people testing the package)

    Kodi changed drastically your code...

2) Fedora maintains a constant updated of [gcc](https://pkgs.org/search/gcc) (each release); when gcc is updated, in the real world the developers isn't interest update your code.... the problem? the packager will need make patches for adapt the code...

[example](http://forum.kodi.tv/showthread.php?tid=263884)

3) Suggestion of others users/packagers

    Updated Kodi to beta release was a suggestion...

4) A beta release, resolves old problems; and delete old or obsolete code.

**Comment by donateur** [comment]
Hello,
Thank you both for your fast replies!

@paulcarroty Thank you - but will not use an old version of software from a repository (eg Kodi 16) when a newer is available.  For security and stability I **always**  update all packages on my system (at least) daily. 

The problem I have, in this example is that, as it is a beta the developers have not classified this software as stable (or production-ready).  My system is more "production" than some at my work!  See https://en.wikipedia.org/wiki/Wife_acceptance_factor


@kuboosoft Thank you, but I'm afraid that your answer is not very clear to me.

I understand that (maintained) software is always being improved and updated, but that doesn't mean that using beta (or alpha!) software is a good choice if you want a stable system.

I understand that you support more than the current stable Fedora release (24), but that's no my  concern, personally.  (See wikipedia link above!!)

I opened this issue to ask if UnitedRPMs has a policy (or some guidelines) for choosing package versions.  This conversation has not changed my opinion that one needs to be written.


I realise that by using this software I rely on the generous time of maintainers here (thank you all very much for that!).  However relying on a maintainer to choose which version is provided is dangerous (and chaotic!)

**For example:**
- The maintainer of the Kodi package wants the latest beta, for some feature they need
- The maintainer of the Kodi-pvr-mythtv package wants a stable version (but has to compile against Kodi beta in the repo)
- The maintainer of libav wants an ancient version from two years ago, because it's easier for them to maintain, despite the fact that it has unpatched critical security issues

If this happened I think we would agree that it would be a disaster.  So I'm asking that a loose version policy be decided on for the packages in this repository.


I suppose that in an ideal world you might have two repositories.  A latest stable repository for the latest stable version of Fedora and a second repository for "beta" software for the beta Fedora version.

Thank you!

**Comment by donateur** [comment]
Hi again,

I have been considering this repository because I want a much newer stable version of Kodi (and Mythtv if you offered it) than is available from other repos like RPMFusion.  I understand that you say RPMFusion is too regulated and that you are trying to avoid that, but could you please have some goals for the stability of packages you provide?

Thank you!

**Comment by paulcarroty** [comment]
> and Mythtv if you offered it

It's planned.

> but could you please have some goals for the stability of packages you provide?

Now we don't have any rules/policy for determination the `stable` or `non-stable` software. Basic features of our package must work, otherwise we don't include it to repository.

If you see the critical bugs or other functionally problems - pls let us know.

**Comment by sergiomb2** [comment]
Hello , I know well RpmFusion 
libav was refused in RPMFusion  https://bugzilla.rpmfusion.org/show_bug.cgi?id=4258
because FFmpeg is almost 100% backwards compatible with libav.
kodi is updated for F25 although last beta or rc failed to build on koji ...

**Comment by kuboosoft** [comment]
@donateur 

> The maintainer of the Kodi-pvr-mythtv package wants a stable version (but has to compile against Kodi beta in the repo)

Why a official 'pvr-addon' needs only  a  Kodi version? Kodi is maintained constantly. When you are a developer you need adapt/update your package, is part of major features. If not the solution is a 'app-image/snap/ FlatPak' package. A example:  Imagine you Kodi 16 needs a specific sqlite version for your correct functionality; Fedora loves sqlite updates constantly. But the Kodi 17 updated your code and was build with a new version of sqlite as result the package works fine. 

Why  I  need make patches and change all only for compile and run correctly the source code, for a version soon replaced for Kodi 17?. We are packagers... the question; works or not works Kodi 17 beta for you?. Other point We also maintain Kodi for Fedora 25/rawhide... and if the project adapts the source code to new dependencies; or people suggest update for valid reasons  welcome ;)

What would be your decision?

If you are afraid for the beta of Kodi, In my [personal project ](https://sourceforge.net/projects/postinstaller/), I maintain the kodi-pvr-addons for Kodi 16... ;)

**Comment by donateur** [comment]
Thank you all for your replies

I tried to make up an example of what could go wrong in my second last post above.  I'm very sorry that it has caused confusion.

I was arguing that if a repo has many people maintaining it, but no policy for choosing what kind of software to release (alpha, beta, stable, old + insecure), the repo could become chaotic.  The repo could end up with conflicting package maturity - some stable, some beta and some old and insecure.


If I understand what you all have written, this repo may not meet my needs, but I do want to thank you for what you are doing!  I will watch how you go in time and will try your repo on a test VM, rather than my "production" system.

@kuboosoft Thank you for the link to your personal project!  kodi 16 + kodi-pvr-mythv are the packages I was looking for - that's very helpful!
