### ISSUE TITLE
Publish repo GPG signature on website

### ISSUE THREAD

**Issue by donateur** [UnitedRPMs/packages#71]
Hello, [the instructions for using this repo](https://github.com/UnitedRPMs/unitedrpms.github.io/blob/master/README.md) ask users to import and verify the GPG key.

The first time any package is installed from the repo users will be prompted to accept the GPG key.  However none is published (at least anywhere I could find).

It is bad practice encouraging users to just accept a security prompt.  Please publish the GPG key signature on the website (which is served over https) and preferably on that instructions page.

Thanks!

**Comment by paulcarroty** [comment]
@donateur 

> However none is published (at least anywhere I could find).

`https://raw.githubusercontent.com/UnitedRPMs/unitedrpms.github.io/master/URPMS-GPG-PUBLICKEY-Fedora-24
` - our GPG key, available from your URL. 

I updated [the Readme](https://github.com/UnitedRPMs/unitedrpms.github.io/blob/master/README.md), hope it now more readable for all.
