### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#74]
@kuboosoft, you're ready for the work? I don't get the answer for my last @ message.

**Comment by kuboosoft** [comment]
Ok; I will see

**Comment by paulcarroty** [comment]
I need a timeout for Monday to rethink the situation and decide what to (not) do next.

**Comment by kuboosoft** [comment]
@paulcarroty  email ;)

**Comment by paulcarroty** [comment]
@kuboosoft we'll make together 50/50 a new website and earn money for infrastructure/maintainers/koji or I say 'goodbye' to URPMS. This is my final point of no return.

Mock and local builds isn't acceptable for my hardware, sorry. Special for chromium/kdenlive/vlc/etc. It's not a small funny hobby anymore.

If you ready for hard work we can continue the adventures, if no - thanks all absolutely without regrets. You should (re)think good about your decision.

**Comment by kuboosoft** [comment]
@paulcarroty proton@...

**Comment by paulcarroty** [comment]
@kuboosoft check the answer.

**Comment by kuboosoft** [comment]
@paulcarroty new problem :( proton@

**Comment by paulcarroty** [comment]
@kuboosoft check the answer and add tutanota to your local client. We don't need to ping here everytime.
