### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#77]
[Some people](https://github.com/nrechn/mock-travis) use $SUBJ for testing/building RPM packages. I think this will be a great idea for URPMS: test every commit and automate building process.

Stages:
* CI works only F24 and F26, we need a new F25 docker image with mock and devtools
* Check task:  test build for every test commit on current `$release`
* If check task have a success - build packages and [push to Github releases](https://docs.travis-ci.com/user/deployment/releases/).
 
Anyone interested? @kuboosoft ?

**Comment by sergiomb2** [comment]
travis is ubuntu how you want test it ?

**Comment by kuboosoft** [comment]
@paulcarroty all new tool for the project is interest for me :)

**Comment by paulcarroty** [comment]
@sergiomb2 https://travis-ci.org/paulcarroty/travis-rpm-test/builds/169954842

@kuboosoft about `docker-rpm-builder`:

* only F23-24
* no Travis integration
* no src.rpm
* sources is much bigger than `mock-travis` if we'll need to change/fix something; Go is more readable and easy than Python

So, there is most hot task on this moment:
* rebuild F25 image with mock and devtools
* enable integration for all repos
* automate Travis rebuild for F25 (shortcoming stable) after every comment
* 'clean builds' and push ready packages to GH releases 

Anyone interested to help me? Because it's too much work and stupid do it only for me.

**Comment by paulcarroty** [comment]
https://docs.travis-ci.com/user/deployment
