### ISSUE TITLE
unitedrpms gpg-agent - what does it do?

### ISSUE THREAD

**Issue by btong** [UnitedRPMs/packages#80]
Have you got any docs on what this is for?

`/var/cache/PackageKit/24/metadata/unitedrpms/gpgdir/S.gpg-agent`

**Comment by paulcarroty** [comment]
@btong this is "not our" part. See the PackageKit docs:

* https://www.freedesktop.org/software/PackageKit/gtk-doc/
* https://help.gnome.org/users/gnome-packagekit/stable/

Guess this is the `gpg-agent` for repositories key.

**Comment by btong** [comment]
Thanks, it's odd that only unitedrpms has one, that's why I opened the issue.

**Comment by btong** [comment]
Aha I can make fedora-cisco-openh264.repo have one too.

It all depends on this setting in the repo file I think:

`repo_gpgcheck=1`

**Comment by paulcarroty** [comment]
`repo_gpgcheck=1`

Repo metadata must be sign by repository owner.
