### ISSUE TITLE
[Important] New package spec guideline

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#81]
All sources, patches, and other resources used in package's `.spec` now need a full web-URL like:

```
Source0:  https://web.site/source.tar.xz
Patch2:     https://web.site/patch1
```

It needs our new TravisCI [app](https://github.com/paulcarroty/mock-travis).

@sergiomb2 @kuboosoft

**Comment by kuboosoft** [comment]
Ok, great; all patches can share via github.... Why our travisCI app need a full path for patches?

**Comment by paulcarroty** [comment]
@kuboosoft https://github.com/UnitedRPMs/packages/issues/84

+ we send you a lot of times invite to slack chat to talk about acestream (dangerous here) + future of URPMS. Your tutanota email was broken?
