### ISSUE TITLE
Farewell, UnitedRPMs!

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#84]
Now I done with Fedora & UnitedRPMs.

Immense gratitude for founders @sergiomb2 and @kuboosoft, issues authors, idea generators, haters and @all contributors. I was happy to work here! and hope the project stay alive.

Sincerely yours,
Paul.

**Comment by sergiomb2** [comment]
I give up on Fedora ? what you use now ?

**Comment by paulcarroty** [comment]
suse.

**Comment by sergiomb2** [comment]
you are the most active member if you go , it should be the end

**Comment by paulcarroty** [comment]
if you lost the interest, you should go. maybe return if go to F again, who knows.

**Comment by kuboosoft** [comment]
@paulcarroty I use Arch Linux as second distro hahaha. Suse isn't for me... OBS isn't friendly... But is more permissive... Do you remember Fuduntu? well, the team migrated to suse... and lost the interest... I am prefer a Mageia....

**Comment by paulcarroty** [comment]
@kuboosoft OBS is great, but have a lot hidden details, for example can't download URL. And you never have the same shit with ffmpeg and Copr with SUSE. 

Arch for kids, Mageia ... I just prefer distro with commercial business-based, it's a guarantee to not die for money reason.

Did you tried to build chromium in OBS?

**Comment by paulcarroty** [comment]
And yep, use two+ distro is a time lost.

**Comment by paulcarroty** [comment]
OK, switch to Slack, github more for dev- and bugtalks.

**Comment by kuboosoft** [comment]
Did you tried to build chromium in OBS?
shhhhhh slack ;)
