### ISSUE TITLE
x264-libs package changed to 10 bit 

### ISSUE THREAD

**Issue by ccaudle** [UnitedRPMs/packages#87]
Package x264-libs-0.148-6.20160912git3f5ed56.fc24.x86_64 changed from 8 bit pixel formats on F24 to 10 bit formats on F25.  That results in output files which do not play properly on many devices such as Roku.  
The same problem came up on OpenSUSE, and according to this email 10 bit formats to not play correctly on iOS or Android devices either:
http://lists.links2linux.de/pipermail/packman/2013-March/011874.html
A build of ffmpeg can use only one bit depth, it cannot support both 8 bit and 10 bit:
http://www.ffmpeg.org/ffmpeg-codecs.html#libx264_002c-libx264rgb

> x264 supports 8- to 10-bit color spaces. The exact bit depth is controlled at x264’s configure time. FFmpeg only supports one bit depth in one particular build. In other words, it is not possible to build one FFmpeg with multiple versions of x264 with different bit depths.

My request would be to revert to 8 bit pixel formats so that output is compatible with the widest range of devices.  I understand there are probably people who want to play high dynamic range content, but it appears that it is not  possible to support both.  Perhaps configuring x264 for 8 bit and x265 for 10 bit would be a good approach (for some reason x265-libs-1.9-3.fc25.x86_64 is configured for 8 bit, but I think devices which can support 10 bit pixels are more likely to be able to support x265 compared to the number of legacy set top boxes, phones, and tablets which have hardware h.264 support that only supports 8 bit pixels).

**Comment by ccaudle** [comment]
I just checked the RPMFusion build, and that build is configured with 8 bit output.
The versions looks really close:
x264-libs-0.148-13.20160924git86b7198.fc25.x86_64
I'm do not understand when United RPMs decides to also build a package available in RPMFusion.  Was the change to 10 bit output here intentional, or an unintentional change?

**Comment by paulcarroty** [comment]
@ccaudle AFAIR x264/*5 was provided by @kuboosoft, wait for his reply.

> I just checked the RPMFusion build, and that build is configured with 8 bit output.

Really?
* https://github.com/rpmfusion/x264/blob/master/x264.spec#L123
* https://github.com/rpmfusion/x264/blob/master/x264.spec#L42

**Comment by ccaudle** [comment]
I don't know what to say, other than I showed the version above (x264-libs-0.148-13.20160924git86b7198.fc25.x86_64) which was installed by removing x264-libs (which removed ffmpeg and several other packages at the same time), then re-installing with --disablerepo=unitedrpms which caused the installation to pull from the RPMFusion repo.

After encoding a file with with ffmpeg using libx264 codec, the output file shows this format:
Stream #0:0: Video: h264 (High), yuv420p, 704x480

With the version from UnitedRPMS the pixel format is shown as yuv420p10le instead of yuv420p.

$ dnf list x264-libs
Installed Packages
x264-libs.x86_64        0.148-13.20160924git86b7198.fc25         @rpmfusion-free
Available Packages
x264-libs.x86_64        1:0.148-6.20160912git3f5ed56.fc24        unitedrpms

**Comment by paulcarroty** [comment]
@ccaudle OK, we should test it. Thanks for the report.

**Comment by kuboosoft** [comment]
Hi! https://github.com/UnitedRPMs/x264/issues/2
