### ISSUE TITLE
VLC broken on F25

### ISSUE THREAD

**Issue by mattiaverga** [UnitedRPMs/packages#89]
On F25 is not possible to install VLC:
```
# dnf install vlc
Ultima verifica della scadenza dei metadati: 0:00:33 fa il Mon Dec  5 16:57:18 2016.
Errore: nothing provides libvpx.so.3()(64bit) needed by ffmpeg-libs-3.1.4-1.fc24.x86_64
```

**Comment by paulcarroty** [comment]
@mattiaverga more info please:

```
# dnf info vlc ffmpeg 
# dnf -vvv install vlc
```

**Comment by mattiaverga** [comment]
`# dnf info vlc ffmpeg
Ultima verifica della scadenza dei metadati: 0:27:59 fa il Mon Dec  5 16:57:18 2016.
Pacchetti disponibili
Nome        : ffmpeg
Arch        : x86_64
Epoca       : 0
Versione    : 3.1.4
Rilascio    : 1.fc24
Dim.        : 1.9 M
Repo        : unitedrpms
Sommario    : Digital VCR and streaming server
URL         : http://ffmpeg.org/
Licenza     : GPLv2+
Descrizione : FFmpeg is a complete and free Internet live audio and video
            : broadcasting solution for Linux/Unix. It also includes a digital
            : VCR. It can encode in real time in many formats including MPEG1
            : audio and video, MPEG4, h263, ac3, asf, avi, real, mjpeg, and
            : flash.

Nome        : vlc
Arch        : x86_64
Epoca       : 0
Versione    : 3.0.0
Rilascio    : 12.20161005git636476b.fc24
Dim.        : 1.5 M
Repo        : unitedrpms
Sommario    : The cross-platform open-source multimedia framework, player and
            : server
URL         : http://www.videolan.org
Licenza     : GPLv2+
Descrizione : VLC media player is a highly portable multimedia player and
            : multimedia framework capable of reading most audio and video
            : formats as well as DVDs, Audio CDs VCDs, and various streaming
            : protocols. It can also be used as a media converter or a server to
            : stream in uni-cast or multi-cast in IPv4 or IPv6 on networks.`

`# dnf -vvv install vlc
cachedir: /var/cache/dnf
Loaded plugins: reposync, Query, playground, system-upgrade, download, config-manager, debuginfo-install, noroot, builddep, protected_packages, copr, generate_completion_cache, needs-restarting
DNF version: 1.1.10
repo: using cache for: fedora
not found updateinfo for: Fedora 25 - x86_64
repo: using cache for: mattia-Astronomy
not found deltainfo for: Copr repo for Astronomy owned by mattia
not found updateinfo for: Copr repo for Astronomy owned by mattia
repo: using cache for: virtualbox
not found deltainfo for: Fedora 25 - x86_64 - VirtualBox
not found updateinfo for: Fedora 25 - x86_64 - VirtualBox
repo: using cache for: fedora-cisco-openh264
not found updateinfo for: Fedora 25 openh264 (From Cisco) - x86_64
repo: using cache for: adobe-linux-x86_64
not found deltainfo for: Adobe Systems Incorporated
not found updateinfo for: Adobe Systems Incorporated
repo: using cache for: unitedrpms
not found deltainfo for: unitedrpms
not found updateinfo for: unitedrpms
repo: using cache for: updates
repo: using cache for: mattia-Testing
not found deltainfo for: Copr repo for Testing owned by mattia
not found updateinfo for: Copr repo for Testing owned by mattia
repo: using cache for: nphilipp-gimp-unstable
not found deltainfo for: Copr repo for gimp-unstable owned by nphilipp
not found updateinfo for: Copr repo for gimp-unstable owned by nphilipp
fedora: usando metadati di Thu Nov 17 11:09:01 2016.
mattia-Astronomy: usando metadati di Mon Dec  5 13:05:53 2016.
virtualbox: usando metadati di Mon Nov 21 22:02:23 2016.
fedora-cisco-openh264: usando metadati di Mon Aug 15 18:30:50 2016.
adobe-linux-x86_64: usando metadati di Mon Nov  7 16:53:12 2016.
unitedrpms: usando metadati di Fri Dec  2 17:30:02 2016.
updates: usando metadati di Sun Dec  4 17:42:39 2016.
mattia-Testing: usando metadati di Mon Dec  5 13:06:05 2016.
nphilipp-gimp-unstable: usando metadati di Mon Dec  5 06:15:56 2016.
Ultima verifica della scadenza dei metadati: 0:29:21 fa il Mon Dec  5 16:57:18 2016.
--> Inizio risoluzione dipendenze
--> Risoluzione delle dipendenze completata
Errore: nothing provides libvpx.so.3()(64bit) needed by ffmpeg-libs-3.1.4-1.fc24.x86_64
(provare ad aggiungere '--allowerasing' alla linea di comando per sostituire i pacchetti in conflitto)`

...maybe the problem is that in F25 libvpx has been upgraded and the soname bumped to libvpx.so.4, so you should rebuild ffmpeg on top of that?

**Comment by mattiaverga** [comment]
Sorry, my fault. Now I see that unitedrpms repo configuration does not automatically update when doing an upgrade of the system.
I've uninstalled the old repo (f24) and installed the new (f25) one, now it works.
