### ISSUE TITLE
Thread of new packages: new versions, updates/upgrades, import, discussion

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#9]
For builds, import, requests etc.

## [How to work with RPM Repository](https://github.com/FedoraUnited/packages/wiki/How-to-work-with-RPM-Repository)

**Comment by paulcarroty** [comment]
@sergiomb2 https://github.com/FedoraUnited/libva-intel-driver is ready.

**Comment by sergiomb2** [comment]
it was best put all in same pool . , i.e. in https://github.com/FedoraUnited/packages/

**Comment by paulcarroty** [comment]
@sergiomb2 It already did; add to RPM repo.

**Comment by sergiomb2** [comment]
yeah , computing it now , instead put binaries in repos , I prefer have binaries just in packages .... 

Anyway I have other ideas , I'd like fork thing from RPMFusion , commit here and make pull request to RPMFusion , i. e. integrate your work in RPMFusion ... when it is possible.

**Comment by sergiomb2** [comment]
@paulcarroty  you only added SRPM ?

**Comment by paulcarroty** [comment]
@sergiomb2 SRPM and RPM, all done.

**Comment by sergiomb2** [comment]
where are the new RPM ? I mean they are not in packages

**Comment by paulcarroty** [comment]
the all new RPM in every repo: 

https://github.com/FedoraUnited/libva-intel-driver

https://github.com/FedoraUnited/smplayer

https://github.com/FedoraUnited/kdenlive

https://github.com/FedoraUnited/minidlna

https://github.com/FedoraUnited/sox-plugins-freeworld

https://github.com/FedoraUnited/deadbeef

https://github.com/FedoraUnited/foobnix

https://github.com/FedoraUnited/cmus

**Comment by paulcarroty** [comment]
@sergiomb2 https://gitlab.com/FedoraUnited/repository/commit/db7e2925bba240b6ccacf965bb2cfe1a1f2ad8e3

**Comment by sergiomb2** [comment]
Thanks, new packages published in google drive ... .
I think have 3 copies is not good , now we have github , bitbucket and gitlab . 
I think we should be more organized ! but for now is good at least we got some packages for F24 
Thanks.

**Comment by paulcarroty** [comment]
New versions: 

* https://github.com/FedoraUnited/libva-intel-driver

* https://github.com/FedoraUnited/deadbeef

 @kuboosoft, **always** write about updates in this thread. We also need no know which packages need rebuilds after updates.

**Comment by paulcarroty** [comment]
@sergiomb2, great. I suggest the next scheme:

* RPM repository - Google Drive and Gitlab (mirror)
* Github for specs, sources, and temporary hosting for rpm/srpm.

**Comment by paulcarroty** [comment]
@sergiomb2 

* https://github.com/FedoraUnited/chromium/releases

* https://github.com/FedoraUnited/chromium-pepper-flash/releases

**Comment by kuboosoft** [comment]
well 3:44 am; the same, I think have 3 copies is not good... I maitain other projects (as postinstallerf and others), and can't sacrifice extra time;  I only will use github; if we need changes, rpm, or sr.rpm updated, is available here. I will update my src.rpm in postinstallerf 900MB aprox for Fedora 24; @paulcarroty  chromium-pepper-flash is provided by postinstallerf https://sourceforge.net/projects/postinstaller/files/fedora/releases/23/SRPM/

**Comment by paulcarroty** [comment]
@kuboosoft go to sleep **RIGHT NOW**. Any zombies will rejected in Fedora United. :smile: 

> I think have 3 copies

**Github for specs and sources**, **Google Drive and Gitlab mirror for RPM repository**. Easy and simple architecture.

If you have updated some SRPM/RPM and need (re)build it - always **write** about it in this thread, someone will add it to RPM repo.

```
Here's the rpm package v.1.2.3, need rebuild.
Here's the rpm package v.1.2.3, ready to push in repo.
```

Thanks all for the work.

@kuboosoft I know about postinstallerf. So, I think we can fork some repos and make our life easier, like a `spotify-client`, `googleplaydownloader`, `kodi`, `popcorn` etc. Just relax, sleep enough and do your work.

We need a website and marketing, maybe other peoples can help us in future.

**Comment by paulcarroty** [comment]
@kuboosoft 

> Also, @paulcarroty . about chromium; I think we should not make a repository for any software here, if the package is not tested...

It's tested, works nice.

**Comment by paulcarroty** [comment]
Updates in RPM repo: chromium, chromium-pepper-flash, deadbeef, libva-intel-driver, idjs+libs https://gitlab.com/FedoraUnited/repository/commits/master

*Hold*: x264, x265 - potentially broken depends and mass rebuild. Need to test. @kuboosoft 

@sergiomb2, make a `git pull` and sync with your RPM repo.

**Comment by sergiomb2** [comment]
@paulcarroty  , I'm trying assimilate all info.
First - close / forget bitbucket , isn't it ? we only work with github and gitlab ? 
Second - I'd like have repos like https://github.com/rpmfusion/ , https://github.com/RussianFedora etc etc , i.e , without src.rpm rpm , tarballs etc , very light repos . 
Third - I'm in this project to see If I can advance work to RpmFusion , so I'd like packages from RPMFusion are the *same* spec , and if not we should fix it on origin , i.e RPMFusion or Fedora . 
For example celt package Why we need celt [1] ? we opus , if we need celt we may unretire it in Fedora . 
About x264. David , why you insists in use devel version instead stable version the difference is usually 12 commits, I don't think have same package just with minor updates helps , kodi, we have kodi in RPMFusion , I got a pull request to updated it to 16.1 [2] .
Other packages that I'd like include in Fedoraunited are things that are not included in RPMFusion yet [3] like mp3splt , freshplayerplugin.
Another example is rtmpdump , rtmpdump is updated in RPMFusion , if not, we should ask in RPMFusion bugzilla to update it [4] that way we can save lot of work , and have things organized etc.

Thanks.
 
[1] https://pkgs.fedoraproject.org/cgit/rpms/celt.git/commit/?id=cfd1704765b500dc46cfbf3cfa2988d9bf797bbe

[2] https://bugzilla.rpmfusion.org/show_bug.cgi?id=4039
https://github.com/mooninite/kodi/commit/a2ef88ccbca352d5f6f55ab23c75ddd506339056

[3]
https://bugzilla.rpmfusion.org/show_bug.cgi?id=33

[4] https://bugzilla.rpmfusion.org/show_bug.cgi?id=4014

**Comment by sergiomb2** [comment]
To be clear another example . mpv , we should fork mpv from RPMFusion [1] , and built it for F24 , if you think mpv.spec may be improved we should ask on RPMFusion , to update it , by send one pull request. 

Bottom line you should be packager maintainer in main sources at first place.  

[1] https://github.com/rpmfusion/mpv

**Comment by sergiomb2** [comment]
by second , I propose put src.rpm rpm only in https://gitlab.com/FedoraUnited/repository or something like that . 
@paulcarroty , have I any update today to add to repo ? I and like the of git pull , by I will syncronize repos right now . 

May I delete xine-lib and fork it from RPMFusion to here ?

**Comment by paulcarroty** [comment]
@sergiomb2 

> have I any update today to add to repo ?

Yes, the last 3 commits - https://gitlab.com/FedoraUnited/repository/commits/master.

**Comment by sergiomb2** [comment]
ah I made a git pull of https://gitlab.com/FedoraUnited/repository/commits/master and now I'm syncing with google drive repo, Thanks

**Comment by sergiomb2** [comment]
> ah I made a git pull of https://gitlab.com/FedoraUnited/repository/commits/master and now I'm syncing with google drive repo, Thanks 

Done

> 
>     have I any update today to add to repo ?
> 
> Yes, the last 3 commits - https://gitlab.com/FedoraUnited/repository/commits/master.
done
> 
>     First - close / forget bitbucket , isn't it ? we only work with github and gitlab ?
> 
> Yep. We can forget about Bitbucket while Gitlab works good, I think. 1 RPM Repo and 1 backup is enough.

OK lets close it . delete it , is to have things more organized !

> 
>     Second - I'd like have repos like https://github.com/rpmfusion/ , https://github.com/RussianFedora etc etc , i.e , without src.rpm rpm , tarballs etc , very light repos .
> 
> Where we will store rpms, srpms before building and testing? It's comfortable. I like the three by @kuboosoft. We also can store all binaries in Github releases.
> 
>     Third - I'm in this project to see If I can advance work to RpmFusion , so I'd like packages from RPMFusion are the same spec , and if not we should fix it on origin , i.e RPMFusion or Fedora .
> 
> I don't have sentiments for RPMFusion. If their package is better than RFR or package from @kuboosoft - no problem, let's use it. A lot of Fusion packages have problems in F24 (too old from F24), and @kuboosoft has modify/update it. Resume - just use the better. Or both if we(I, you etc) need it. About celt/opus etc - please open personal issue for each.
> 

RFR you mean Russian Fedora isn't it ? I think Russian Fedora begin have ffmpeg , because RPMFusion is stopped and we by the same reason. We have 2 goals, IMO , one is replace RPMFusion in F24 (and rawhide ?!)  in what is essential and second provide packages (and updates) that aren't in Fedora and RPMFusion . When is a package that already exist in others repos and we have fixes or update, we should try downstream the fixes or updates, but not always is possible.

>     About x264. David , why you insists in use devel version instead stable version
> 
> This is right decision 'cause the old (stable) versions can be build in F24.

No, it is not, matter of fact, I have x264-0.148-6.20160412gitfd2c324.fc23.x86_64 ready to commit in RPMFusion , now we have x264-0:0.148-5.20160118git5c65704.fc23.x86_64 just one git push behind .

>     Other packages that I'd like include in Fedoraunited are things that are not included in RPMFusion yet [3] like mp3splt , freshplayerplugin.
> 
> Great, try to build and add in src repo if you can maintain it. 

OK ;) I also have the builder project to do ...

**Comment by kuboosoft** [comment]
Hi, the purpose about maintain updated packages as x264 and x265 is the compatibility with updates about vlc (vlc/videolan maintains x264 and x265) and ffmpeg; celt above time was marked orphan;  I needed 'celt' in Kodi; and ffmpeg. The src.rpm and rpm in github is only for test purpose, Nevertheless; before publishing I have installed and tested. Other purpose is give a beatiful rpmlint to src.rpm o foo.rpm; mantain a solution for people in rawhide; learn make rpm; give a mode light as COPR; maybe I am crazy but a I have a dream of a Fedora LTS; or  a rolling-release model. Fuduntu was a beatiful project.. Sorry my english isn't good.

**Comment by paulcarroty** [comment]
@sergiomb2 

> OK lets close it . delete it , is to have things more organized !

Deleted.

> We have 2 goals, IMO

My goal is creating the best additional repository for Fedora 24+ and back-port the best packages from Russian Fedora, RPM Fusion etc. Users will enable our repo and get all what they want without mixing RFR and Fusion, maintainers will create the packages as they want without bureaucracy.

> (and rawhide ?!)

I use FE now in Rawhide, all works good. Yep, Rawhide is very dynamical distro with latest software and we'll have the problems with gstreamer-related packages, this is fixable. Anyway, now I have not enough electricity for mass rebuild to Rawhide :smile:

**Comment by kuboosoft** [comment]
@paulcarroty @sergiomb2 ffmpeg updated (minors changes, without opencv); vlc (updated and without opencv); libav (minors changes without opencv); all system working in rawhide...

**Comment by sergiomb2** [comment]
I will publish libmp3splt and mlt update ! , with this ones we may build other mp3splt packages and update kdenlive , also should already be able to build 
https://github.com/rpmfusion/libopenshot-audio
https://github.com/rpmfusion/libopenshot 
https://github.com/rpmfusion/openshot

**Comment by sergiomb2** [comment]
we can close this ticket ? , openshot, libmp3splt and mlt are published  .

**Comment by paulcarroty** [comment]
@sergiomb2 why? This packages isn't the last in URPMS, we'll add something new in future.

**Comment by sergiomb2** [comment]
we have other ticket for that isn't it ? , or do a new ticket , this one have already a lot of information , IMHO.

**Comment by paulcarroty** [comment]
OK.
