### ISSUE TITLE
Outdated chromium-libs-media-freeworld

### ISSUE THREAD

**Issue by avibrazil** [UnitedRPMs/packages#90]
We are already on version 55 but this package — version 53 — is holding chromium update. Also, it brakes the browser completely with the "aw snap" message right after you start it.

**Comment by paulcarroty** [comment]
Ping @kuboosoft

**Comment by paulcarroty** [comment]
+ all chromium packages was deleted from F25 as partial fix.

**Comment by avibrazil** [comment]
What is the solution to watch Netflix on Fedora with shipped Chromium ?

**Comment by kuboosoft** [comment]
@avibrazil Don't worry!! the task finished, but I need Invert in new hardware.... [I accept donations](http://www.ebay.es/itm/100-Working-Core-2-Quad-Q6600-Processor-Slacr-2-4Ghz-8Mb-1066Mhz-Socket-775-649-/252685782342?hash=item3ad53f0d46:g:NZwAAOSwEzxYVSQJ) haha

**Comment by paulcarroty** [comment]
@kuboosoft [It's](http://www.ebay.com/itm/Intel-Core-i5-6500-Skylake-Soket-1151-LGA-3-2Ghz-SR2BX-CPU-Processor-DDR4-/172332053362?hash=item281fca7372:g:kqAAAOSwknJXzozS) is too much better.

**Comment by avibrazil** [comment]
Where is it? There is no chromium-libs-media-freeworld available to dnf. Is it available somewhere for a direct download?

**Comment by paulcarroty** [comment]
@avibrazil https://sourceforge.net/projects/unitedrpms/files/25/x86_64/

@kuboosoft Fedora's version rewrite your package. Use `Epoch` or update to `55.0.2883.87`.

**Comment by avibrazil** [comment]
It sounds too complicated or I don't have enough knowledge for that. Why a simple dnf update or dnf install doesn't work? This was supposed to be a simple procedure.

**Comment by paulcarroty** [comment]
@avibrazil I hope @kuboosoft (our maintainer) will solve it, I wrote above about the problems.

You can try the test build via `# dnf erase chromium && dnf install https://sourceforge.net/projects/unitedrpms/files/25/x86_64/chromium-55.0.2883.75-2.fc25.x86_64.rpm https://sourceforge.net/projects/unitedrpms/files/25/x86_64/chromium-libs-55.0.2883.75-2.fc25.x86_64.rpm https://sourceforge.net/projects/unitedrpms/files/25/x86_64/chromium-libs-media-freeworld-55.0.2883.87-2.fc25.x86_64.rpm`

**Comment by avibrazil** [comment]
This is much better, thanks.
I'll test it later today and I hope those other problems get fixed so we can use plain dnf install

**Comment by avibrazil** [comment]
@paulcarroty so I used your command which fails apparently because the freeworld package has a different version (87) from the main chromium package (75) on that repo.

If I install the freeworld package (87) RPM plus the official chromium packs from Fedora (also 87), regular browser works but Netflix doesn't work. I imagine the freeworld plugins were supposed to be listed on browser extensions, but they are not.

So Netflix still not working.

Thank you in advance

**Comment by kuboosoft** [comment]
@avibrazil test now! 

```
su
dnf clean metadata && dnf -y update
```
@paulcarroty if we use epoch tag, is a problem for our users; example they can not install anymore the chromium fedora (I need think about it)...  about the hardware my motherboard uses socket LGA775; dedicated exclusive to Fedora... haha

**Comment by paulcarroty** [comment]
@kuboosoft @avibrazil It works: 

```
# dnf clean all && dnf install chromium-freeworld
Last metadata expiration check: 0:02:01 ago on Fri Dec 30 11:03:01 2016 EET.
Dependencies resolved.
================================================================================
 Package                        Arch    Version               Repository   Size
================================================================================
Installing:
 chromium                       x86_64  53.0.2785.143-3.fc26  unitedrpms   28 M
Installing dependencies:
 chromium-libs                  x86_64  53.0.2785.143-3.fc26  unitedrpms   33 M
 chromium-libs-media-freeworld  x86_64  53.0.2785.143-3.fc26  unitedrpms  1.4 M
 libatomic                      x86_64  6.3.1-1.fc26          rawhide      36 k
 minizip                        x86_64  1.2.8-10.fc24         rawhide      37 k

Transaction Summary
================================================================================
Install  5 Packages

Total download size: 63 M
Installed size: 217 M
Is this ok [y/N]: y
```

> example they can not install anymore the chromium fedora

OK, split to chromium vs chromium-freeworld looks more clever.

I see your experiments with CI services was failed; it means that chromium's question isn't resolved, @kuboosoft.

**Comment by paulcarroty** [comment]
P.S. Chromium crashed "Aw, snap!" in F26.


[trace.txt](https://github.com/UnitedRPMs/packages/files/678498/trace.txt)

**Comment by avibrazil** [comment]
Now I have chromium and chromium*freeworld version 87, both from unitedrpms. The browser works. But Netflix video player still doesn't.

**Comment by kuboosoft** [comment]
@avibrazil Because unitedrpms doesn't provide the chromium-widevine, is momentarily (tecnical issues); I need make a git repository from my project (postinstallerf); but the next hours I will put here ;) don't worry. I have muchs packages, updating or rebuilding. I Accept donations hahaha. 

@paulcarroty 
My experiments of Chromium with CI services was failed, thanks a limit time, example circle ci (takes 2 hours) is bad; chromium needs 4 hours haha; and other services you can't run mock... a issue no solved and reported in [bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1336750)...the '--cap-add=SYS_ADMIN' isn't permited for various CI services...

**Comment by paulcarroty** [comment]
OK, hardware problems -> slack; issue with now fixed. 

Thanks all and 

![happy-new-year-2017-hd-images](https://cloud.githubusercontent.com/assets/1550705/21577085/79d06b5a-cf56-11e6-8a05-1d3b6d99f66e.jpg)

**Comment by avibrazil** [comment]
Issue is not solved. Please reopen

**Comment by kuboosoft** [comment]
@avibrazil Happy hacking buddy!!
close chromium...
```

su
dnf clean all
dnf -y update && dnf -y install chromium-pepper-flash chromium-widevine
```
**Good news!! Now we provide" flash player plugin" native for Firefox**

`dnf -y install flashplugin`

Please reports if it works for you...

**Comment by avibrazil** [comment]
Noooooow Netflix works. Like that:

`dnf -y install
        chromium-pepper-flash
        chromium-widevine
        chromium`

I also noticed chromium-libs-media-freeworld getting installed, but I'm not sure if it necessary anymore.

So this is it. Next steps I would suggest to check the dependencies and decide maybe make an easier meta-package that does the entire job, like a simple "chromium-freeworld".

Thank you

**Comment by kuboosoft** [comment]
There are people who prefer everything separated; We can not unify.  
But I can change, example; If our chromium detects such packages, it is installed automatically or we can add the steps in our wiki (I am prefer the wiki).

**Comment by avibrazil** [comment]
I understand, but there is no sense in installing widevine without chromium, so a dependency is required in my opinion

Thank you for your efforts to fix this

**Comment by paulcarroty** [comment]
https://github.com/UnitedRPMs/chromium-freeworld/commit/19b5b5113ba3c305ef664634b84b5fc20385fb18
