### ISSUE TITLE
Various problems with vlc: stale plugins cache, libva integration

### ISSUE THREAD

**Issue by roweryan** [UnitedRPMs/packages#91]
I am getting lots of errors about a stale plugins cache:

```
$ vlc
(truncated)
[000055fb172fc1c8] core libvlc error: stale plugins cache: modified /usr/lib64/vlc/plugins/access/libsftp_plugin.so
(truncated)
```

I am also not seeing any hardware acceleration when using libva-intel-driver - can anyone else test this? I have tried forcing it both in the gui (was set to auto) and with --ffmpeg-hw 

```
$ rpm -q vlc libva-intel-driver
vlc-3.0.0-15.20161122gitccfdb5a.fc25.x86_64
libva-intel-driver-1.7.2-1.fc25.x86_64
```

**Comment by paulcarroty** [comment]
Thx for report, wait for update.

**Comment by paulcarroty** [comment]
@roweryan the latest version was pushed to repository.

Please test it via `# dnf clean all && dnf update`

**Comment by roweryan** [comment]
It's worse now, vlc still has the stale plugins cache, then it complains about wayland, then it crashes:

```
$ rpm -q vlc libva-intel-driver
vlc-3.0.0-16.20161228git368f85d.fc25.x86_64
libva-intel-driver-1.7.3-1.fc25.x86_64
$ vlc
VLC media player 3.0.0-git Vetinari (revision 345754b)
[000056391280c108] core libvlc error: stale plugins cache: modified /usr/lib64/vlc/plugins/access/libaccess_alsa_plugin.so
[000056391280c108] core libvlc error: stale plugins cache: modified /usr/lib64/vlc/plugins/access/libaccess_archive_plugin.so
[000056391280c108] core libvlc error: stale plugins cache: modified /usr/lib64/vlc/plugins/access/libaccess_concat_plugin.
(more)
[000056391280c108] core libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
This application failed to start because it could not find or load the Qt platform plugin "wayland"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

**Comment by roweryan** [comment]
I tried a reinstall, that didn't fix it.

**Comment by paulcarroty** [comment]
Strange, it works on F26. Try to delete old config via `rm -rvf ~/.config/vlc/`.

**Comment by roweryan** [comment]
Doesn't change anything :(

**Comment by roweryan** [comment]
Only thing that looks weird in strace is this:

`[pid 10190] stat("/usr/bin/platforms/.", 0x7fd4061e9250) = -1 ENOENT (No such file or directory)`

**Comment by paulcarroty** [comment]
@roweryan the same error into F25 Wayland session. What about X-session?

Ping @kuboosoft

**Comment by paulcarroty** [comment]
UPDATE: this bug only inside Wayland-session

**Comment by kuboosoft** [comment]
I will test!! in this moment some videos crashed.

**Comment by paulcarroty** [comment]
It's can be the upstream bug. I've added many Wayland- and Qt-related depends in test build: https://github.com/UnitedRPMs/travis-rpm-builder/releases , but the problem's still exist.

**Comment by kuboosoft** [comment]
@paulcarroty @roweryan 
Well; test it now! Now vlc has wayland support ;)

su 
dnf clean all && dnf -y update

**Comment by kuboosoft** [comment]
@paulcarroty vlc and wayland, is in a medium stage ... I remember when I enabled wayland in Fc23 and vlc crashes constantly... but f25 and superior should works fine... I am playing videos above 8 hours without problem, in wayland...

**Comment by paulcarroty** [comment]
> I am playing videos above 8 hours without problem
Pornmaniac with unlimited free time?

>  but f25 and superior should works fine
Every time when I started vlc and open the video see new clear window (something like mpv) with multimedia. Seems like a compositor's(GShell) problem.

**Comment by roweryan** [comment]
vlc coredumps for me. If I delete ~/.config/vlc/ it starts then the second time it coredumps.

Also hidpi is making everything huuuge!

**Comment by paulcarroty** [comment]
GNOME 3.23, Wayland session

![screenshot from 2017-01-06 14-15-05](https://cloud.githubusercontent.com/assets/1550705/21717718/88553fec-d41b-11e6-8a9b-fbd8e63e8efb.png)

**Comment by roweryan** [comment]
I tested with latest Fedora 25 and the Mad Max Fury Road 1080p trailer, and with big buck bunny.

**Comment by kuboosoft** [comment]
@paulcarroty 

> Pornmaniac with unlimited free time?

hahaha, yes various xxx videos hahaha, naaa, I downloaded music videos (80's) for my Ipad ;)

@paulcarroty @roweryan Why no change to XFCE? + Lighdm;  It solves the problem... but the best choice is report it in [vlc](https://trac.videolan.org/vlc/)

**Comment by roweryan** [comment]
@kuboosoft Change to another desktop environment because vlc is core dumping :frowning:

**Comment by kuboosoft** [comment]
@roweryan or make your contribution helping [here](https://fedoraproject.org/wiki/Common_F25_bugs#Certain_Qt_5_apps_.28VLC.2C_Calibre.29_are_scaled_up_or_down_when_they_should_not_be)

**Comment by kuboosoft** [comment]
@paulcarroty @roweryan can you test it?... I need check it it works for you... and apply the changes in the new updates ;)

Edit your **"/usr/share/applications/vlc.desktop"**

Replacing:

`Exec=/usr/bin/vlc --started-from-file %U`

by

`Exec=sh -c "QT_AUTO_SCREEN_SCALE_FACTOR=0 && /usr/bin/vlc --started-from-file %U"`

Doesn't work?

Replace with 

`Exec=sh -c "QT_AUTO_SCREEN_SCALE_FACTOR=0 && /usr/bin/vlc --started-from-file %U"`

**Comment by roweryan** [comment]
vlc-core-3.0.0-19.20170104gitf8f5395.fc25.x86_64

The first works for me, so does the second. No more segfault, but still a stale plugins cache.
