### ISSUE TITLE
The transmisson-sequential's craches on F25

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/packages#92]
Traces:

* https://github.com/UnitedRPMs/unitedrpms.github.io/files/667915/backtrace.txt
* https://github.com/UnitedRPMs/unitedrpms.github.io/files/658800/coredump.zip

Spec: https://github.com/UnitedRPMs/transmission-sequential/blob/master/transmission-sequential.spec

Build logs: https://travis-ci.org/UnitedRPMs/transmission-sequential/builds

Submitted by @NTMan

**Comment by paulcarroty** [comment]
@NTMan, try to work with new test build: https://github.com/UnitedRPMs/travis-rpm-builder/releases/tag/transmission-sequentialFEDORA-25-X86_64201701012101

**Comment by NTMan** [comment]
New test build transmisson-sequential not associated with .torrent files.

![screenshot from 2017-01-03 18-47-16](https://cloud.githubusercontent.com/assets/200750/21609629/4e4a9992-d1e5-11e6-86a8-b4275e79af2b.png)

**Comment by paulcarroty** [comment]
Select the torrent-file -> Properties -> Open With -> transmission

What about crashes?

**Comment by NTMan** [comment]
> Select the torrent-file -> Properties -> Open With -> transmission

`Open With` tab is absent.
![screenshot from 2017-01-03 21-29-46](https://cloud.githubusercontent.com/assets/200750/21614617/fb4df24a-d1fb-11e6-9813-ef6a8a0178e1.png)



> I need at least a week to watch.

I need at least a week to watch.

**Comment by paulcarroty** [comment]
![screenshot from 2017-01-03 22-28-33](https://cloud.githubusercontent.com/assets/1550705/21621975/164e0e92-d204-11e6-8f2e-fb3599fac7c9.png)
