### ISSUE TITLE
rebuild kodi with libcec support for fc24

### ISSUE THREAD

**Issue by czipis** [UnitedRPMs/packages#93]
Hi David,
current kodi rpm for fc24 has not been built with libcec enabled (17.0rc2-1.20161230git5c40b5c.fc24)
here is the warning from kodi.log
WARNING: CreatePeripheral - libCEC support has not been compiled in, so the CEC adapter cannot be used.

previous version (17.0b2-1.20160926gitaa5d1e5.fc24) worked fine with libcec

**Comment by kuboosoft** [comment]
@czipis I need solve the detection of libcec for Fc24 (I disabled temporally)... but fc25 and rawhide is enabled...
