### ISSUE TITLE
nvidia packages: bump to 375.26 for newer Fedora kernel compatibility

### ISSUE THREAD

**Issue by scottlinux** [UnitedRPMs/packages#96]
Hi, thank you for this awesome set of packages. 

Is it possible to update rpms for the latest nvidia stable version, 375.26?

The current nvidia version provided 370.23 understandably does not appear to be able to be built via dkms on current Fedora 25 kernels (4.9+). I am not certain that 370.23 supports kernel 4.8 or newer.

dkms build output:

[fedora25_nvidia_370_23.txt](https://github.com/UnitedRPMs/packages/files/728245/fedora25_nvidia_370_23.txt)

**Comment by scottlinux** [comment]
Apologies- I think I created this in the wrong issue tracker?

https://github.com/UnitedRPMs/nvidia-driver/issues

**Comment by paulcarroty** [comment]
Ping @kuboosoft, I done my deals with NVidia.

Also suggest to try negativo17's [repo](http://negativo17.org/nvidia-driver/).

**Comment by kuboosoft** [comment]
@paulcarroty What happened? and your nvidia video card?
