### ISSUE TITLE
Feature request : patch chromium to enable vaapi hardware video decode

### ISSUE THREAD

**Issue by sheepdestroyer** [UnitedRPMs/packages#97]
Could you patch chromium to enable vaapi hardware video decode? That would be such a game changer.
As : 
https://aur.archlinux.org/packages/chromium-vaapi/ 
        chromium_vaapi.patch
        chromium_vaapi-intel.patch
        chromium_vaapi-other.patch

edit, updated one : https://github.com/SoundSonic1/PKGBUILD-Arch-Linux

**Comment by kuboosoft** [comment]
@sheepdestroyer but vaapi is experimental... can you [clone](https://github.com/UnitedRPMs/chromium-freeworld) the repo, apply the patches and rebuild?

**Comment by sheepdestroyer** [comment]
Would like to try but this repo is just a set of patchs. Never tryied to build chromium yet and there is no doc as to how to get original source, merge UnitedRPMs patches, and then build.

Do you have build instructions so I can first try to replicate UnitedRPMs build?

**Comment by kuboosoft** [comment]
You only need moc (easy)... and needs apply the patches with vaapi, and wait 10hours  with the build :/. Yes 10 hours...
