### ISSUE TITLE
N1 won't install due to wrong dependancy

### ISSUE THREAD

**Issue by rhmk** [UnitedRPMs/packages#98]
The current N1 package will not install due to missing dependancy on Fedora 25. the current nodejs implementation provides v8-abi 5.1 and no older/compatibility package provide v8-abi= 5.0

> \# dnf install n1
> Failed to set locale, defaulting to C
> Last metadata expiration check: 0:17:49 ago on Sun Feb 19 11:17:11 2017.
> Error: nothing provides **nodejs(v8-abi) = 5.0** needed by n1-0.4.33-1.gite8f137e.fc25.x86_64
> (try to add '--allowerasing' to command line to replace conflicting packages)

The current nodejs package provides abi 5.1:
 

> \# rpm -q --provides nodejs
> bundled(c-ares) = 1.10.1
> bundled(http-parser) = 2.7.0
> bundled(v8) = 5.1.281.89
> nodejs = 1:6.9.5-1.fc25
> nodejs(abi) = 6.9
> nodejs(abi6) = 6.9
> nodejs(engine) = 6.9.5
> **nodejs(v8-abi) = 5.1**
> nodejs(v8-abi5) = 5.1
> nodejs(x86-64) = 1:6.9.5-1.fc25
> nodejs-punycode = 2.0.0
> npm(punycode) = 2.0.0

Can anyone change the requirement to >= 5.0 or will n1 break with that dependancy?

**Comment by paulcarroty** [comment]
N1 will be deleted from URPMS because the source was closed.

**Comment by kuboosoft** [comment]
It only changed your name... https://github.com/nylas/nylas-mail
Provides:n1 >= %{version}-%{release} ; That's all!

**Comment by paulcarroty** [comment]
It's the fake open source, like a telegram.

**Comment by kuboosoft** [comment]
In a world ruled by thunderbird and others ... is bad...

**Comment by rhmk** [comment]
Wanted to give it try, as it looked promising alternative to thunderbird. Too bad.
 Thank you
