### ISSUE TITLE
openssl-full-libs execstack bit

### ISSUE THREAD

**Issue by dcrdev** [UnitedRPMs/packages#99]
The openssl-full-libs package has been created with an libcrypto.so.10 library that has had the execstack bit set at compile time.

```execstack -q /usr/lib64/libcrypto.so.10```
```+ /usr/lib64/libcrypto.so.10```

Libraries should almost never have the execstack bit set and this is causing a number of selinux denials resulting in a number of core services that utilise openssl to fail including ssh and mysql.

Also I'm a bit annoyed that openssl-full-libs has been set to replace openssl-libs, I'm not entirely clear on why you need an independently packaged version of openssl. I'm sure there is a valid reason, but I don't think it should be replacing stock packages in this manner.

**Comment by sergiomb2** [comment]
hi, no you don't need openssl-full now openssl-freeworld so 
dnf distro-sync --disablerepo=unitedrpms "openssl*"

@kuboosoft maybe we should add obsoletes / provides to openssl-freeworld of openssl-full

about execstack , it may take some time to fix it ... I have selinux disabled ...

> Libraries should almost never have the execstack bit set and this is causing a number of selinux denials resulting in a number of core services that utilise openssl to fail including ssh and mysql.

ah that could be the problem reported in other threads 

> Also I'm a bit annoyed that openssl-full-libs has been set to replace openssl-libs, I'm not entirely clear on why you need an independently packaged version of openssl. I'm sure there is a valid reason, but I don't think it should be replacing stock packages in this manner.

openssl-freeworld is just useful for tribler package and acestream (not packaged) .

sorry for the trouble maybe the better is disable selinux wgile fix open-ssl package
